      SUBROUTINE ASDPMD (IN,AOUT,DEC,DECWR,WORDSZ)
C
C     CONVERT RIGHT-JUSTIFIED 16-BITS OF UNPACKED ASCII STORED IN 
C     INTEGER OF LENGTH (WORDSZ) BITS TO LEFT-JUSTIFIED CHARACTER
C     DEC - BYTE SWAP; ALL OTHERS - SHIFT (NBSHIFT) BITS LEFT
C      ONLY DEC: LITTLE ENDIAN - BYTES ORDERED L-R (4,3,2,1)
C     ALL OTHER:   BIG     "   -   "      "     "  (1,2,3,4)
C
C     IN   - INPUT INTEGER VALUE
C     AOUT - OUTPUT CHARACTER VALUE
C
      CHARACTER*8 AOUT

      IF(DEC.EQ.1.0 .AND. DECWR .EQ. 0.)THEN
         CALL SWAP16(IN)
         IOUT=IN
      ELSE IF(DEC .EQ. 0. .AND. DECWR .EQ. 0.)THEN
         NBSHIFT=WORDSZ-16
         IOUT=ISHFT(IN,NBSHIFT)
      ELSE IF(DEC .EQ. 1.0 .AND. DECWR .EQ. 1.0)THEN
         IOUT=IN
      ELSE IF(DEC .EQ. 0. .AND. DECWR .EQ. 1.0)THEN
         CALL SWAP16(IN)
         NBSHIFT=WORDSZ-16
         IOUT=ISHFT(IN,NBSHIFT)
      END IF
      WRITE(AOUT,15)IOUT
 15   FORMAT(A2)
      RETURN
      END
