c
c----------------------------------------------------------------------X
c
      SUBROUTINE CALIB(DBM,RADCON)

C     ROUTINE TO CALCULATE THE RADAR CONSTANT AND SET LOOKUP
C     TABLE TO CONVERT INTEGER TAPE DATA VALUES TO DBM POWER
C     VALUES FOR HRD FORMAT DATA.  A LINEAR RELATION IS ASSUMED
C     BETWEEN THE INTEGER AND DBM VALUES.
C
C     C1,C2- INTERCEPT AND SLOPE FOR THE LINE RELATING INTEGER
C            TAPE VALUES TO DBM, I.E., DBM = C1 +C2*(ITAPE-1)
C            WHERE ITAPE IS THE INTEGER TAPE VALUE.
C

      DIMENSION DBM(256)

      DATA PT,PW,G,BW,WL/85.7,4.0,38.1,2.0,10.42/
      DATA C1,C2/-123.0,0.5/


      DO 10 I=1,256
 10      DBM(I)=C1+C2*(I-1)
      GAIN=10.**(G/10.)
      RADCON=2.505E22*WL*WL/(GAIN*GAIN*BW*BW*0.52452*PW)
      RADCON=10.*ALOG10(RADCON)-PT
      PRINT 20,RADCON
 20   FORMAT(1X,'HRD (CALIB): Radar constant= ',F8.1,/)
      RETURN
      END



