c
c----------------------------------------------------------------------X
c
      SUBROUTINE RESETBG(IOLDGY,IGRPLT,BGFLAG,GRAYTYP,GSTR,GRAYEST)
C
C  RESET BACKGROUND/FOREGROUND COLORS AND RESTORE RAINBOW COLOR TABLE
C
      CHARACTER*1 BGFLAG
      CHARACTER*4 GRAYTYP

      IOLDGY=0
C      CALL GSCR(1,0,0.,0.,0.)
      IGRPLT=0
      CALL SETCOL(IGRPLT,BGFLAG,GRAYTYP,GSTR,GRAYEST)
      RETURN
      END
