c
c----------------------------------------------------------------------X
c
      SUBROUTINE SCANERR(DAT,IOUT,BDVAL,MNGATE,MXGATE,NANG,AZA,ELA,
     X                   FXOLD,AZROT,BAZ,ITPOLD,MXR,MXA,MXF)
C
C  FUNCTION - SCANERR: F(OUT)=SCANNING ANGLE ERROR (TRUE-ACTUAL)
C
C     AZA,ELA - AZIMUTH (SCANNED) AND ELEVATION (FIXED) ANGLES OF THE
C               SCANNING RADAR
C     FXOLD   - NOMINAL FIXED ANGLE.  FOR COPLANE SCANNING, THIS IS
C               THE COPLANE ANGLE AND ELC IS THE CORRESPONDING NOMINAL
C               ELEVATION ANGLE COMPUTED AT THE CURRENT AZIMUTH.
C     AZROT   - ROTATION ANGLE OF SCAN (SEE RDFF AND RDUF)
C     BAZ     - AZIMUTH ANGLE OF THE BASELINE
C
C     IOUT   - OUTPUT FIELD NUMBER
C
      DIMENSION DAT(MXR,MXA,MXF),AZA(MXA,2),ELA(MXA,2)
      DIMENSION AZROT(8)
      DATA RE,TORAD,TODEG/17000.0,0.017453293,57.29577951/

      TANFX=TAN(FXOLD*TORAD)
      DO 100 J=1,NANG
         SINA=SIN((AZA(J,1)-AZROT(ITPOLD)-BAZ)*TORAD)
         IF(ITPOLD.EQ.2)THEN
            ELC=TODEG*ATAN(ABS(SINA*TANFX))
         ELSE
            ELC=FXOLD
         END IF
         ERRANG=ELC-ELA(J,1)
         DO 90 I=1,MXR
            DAT(I,J,IOUT)=BDVAL
            IF(J.GT.NANG .OR. I.LT.MNGATE .OR. I.GT.MXGATE)GO TO 90
            DAT(I,J,IOUT)=ERRANG
   90    CONTINUE
  100 CONTINUE
      RETURN
      END
