      SUBROUTINE COPCX(CO,CI,N)
C
C     THIS SUBROUTINE COPIES ONE CHARACTER ARRAY TO ANOTHER
C
C     CI- INPUT ARRAY
C     CO- OUTPUT ARRAY
C
      CHARACTER*(*) CI(1),CO(1)
      DO 10 I=1,N
         CO(I)=CI(I)
 10   CONTINUE
      
      RETURN
      END
