      SUBROUTINE DIGITP(KRD,IBUF,RBUF,IPR)
C
C        GENERATES THE SPECIFICATIONS FOR AND PRODUCES DIGITAL DISPLAYS
C                  OF THE CARTESIAN DATA.
C
      INCLUDE 'CEDRIC.INC'
      COMMON /VOLUME/ INPID(NID),ID(NID),NAMF(4,NFMAX),SCLFLD(NFMAX),
     X                IRCP(NFMAX),MAPVID(NFMAX,2),CSP(3,3),NCX(3),
     X                NCXORD(3),NFL,NPLANE,BAD
      CHARACTER*2 NAMF
      COMMON /DSPECS/ IWIND(2,3),PWIND(2,3),NCWORD(3),IFLDW(NFMAX),
     X                SCLFAC(NFMAX),NSYMCD(2,NFMAX),WIDCD(NFMAX),
     X                ZREFCD(NFMAX),THKLIN(NFMAX)
      COMMON /AXUNTS/ IUNAXS,LABAXS(3,3),SCLAXS(3,3),AXNAM(3)
      CHARACTER*4 AXNAM
      CHARACTER*1 IDEST,LF,IWOP
      CHARACTER*2 NAME(4)
      CHARACTER*3 ITEST
      DIMENSION IBUF(1),RBUF(1),IDSEND(2),NDGDSP(NFMAX)
      CHARACTER*(*) KRD(10)
      CHARACTER*8 NAMIN
C
C        INITIALIZE DIGITAL DISPLAY PARAMETERIZATION
C
      READ (KRD,100)IDEST,LF,RSKP,IWOP
C  100 FORMAT(8X,A1,7X,A1,7X,F8.0,40X,A1)
 100  FORMAT(/A1/A1/F8.0//////A1)
      LSKP=MAX1(RSKP,1.0)
      CALL WINSET(IWIND,PWIND,IWOP)
      CALL SETAXS(NCWORD,LF,IPR)
      CALL SELDEV(IDSEND,N,IDEST)
C
C        ESTABLISH FIELDS, SCALE FACTORS AND NO. OF DIGITS
C
      CALL CONFLD(IFLDW,NFMAX,0)
   10 CONTINUE
C
C        READ ANOTHER FIELD CARD
C
      CALL KARDIN(KRD)
      CALL COMCHK(IPR,KRD)
      READ (KRD,101)ITEST,NAMIN,SCL,RDIG
C  101 FORMAT(A3,5X,A8,2F8.0)
 101  FORMAT(A3/A8/F8.0/F8.0)
      IF(ITEST.EQ.'END') GO TO 20
      IF(SCL.EQ.0.0) SCL=1.0
      NDIG=RDIG
      IF(NDIG.LE.0.OR.NDIG.GT.8) NDIG=3
      CALL FLDSET(NAMIN,NAMF,IFLDW,1,NST)
      IF(NST.NE.0) GO TO 10
      CALL FLDSETR(NAMIN,NAMF,SCLFAC,SCL,NST)
      CALL FLDSET(NAMIN,NAMF,NDGDSP,NDIG,NST)
      GO TO 10
   20 CONTINUE
C
C        GENERATE DISPLAYS AND SEND THEM TO THE APPROPRIATE DEVICES
C
      CALL PLNFLD(IFIXAX,L1,L2,NFDSP)
      IF(NFDSP.EQ.0) GO TO 91
      DO 80 L=L1,L2,LSKP
         JFLD=0
         DO 75 I=1,NFDSP
   71       CONTINUE
C
C           SEARCH FOR THE NEXT ACTIVE FIELD FOR DISPLAY
C
               JFLD=JFLD+1
               IV=MAPVID(JFLD,2)
               IF(IFLDW(IV).EQ.0) GO TO 71
            CALL NEXACT(IFIXAX,L,IV,RLEV,NAME,1)
            CALL FETCHD(IN,ID,L,JFLD,IBUF,RBUF,N1,N2,
     X                  IFIXAX,BAD,RLEV,NST)
C
C              PRODUCE THE DIGITAL DISPLAY
C
            DO 74 M=1,N
               CALL RITER(IDSEND(M),RBUF,N1,N2,BAD,IWIND,PWIND,
     X                    SCLFAC(IV),NDIG,NCWORD,RLEV,NAME)
   74       CONTINUE
   75    CONTINUE
   80 CONTINUE
   90 CONTINUE
      RETURN
   91 CONTINUE
      CALL CEDERX(539,0)
      RETURN
      END
