      FUNCTION FUNK(YVAL,CF,NCF)
C
C        EVALUATES A POLYNOMIAL FUNCTION WHOSE COOEFFICIENTS ARE
C                  GIVEN IN CF (ORDER= NCF-1) AT ORDINATE VALUE=YVAL
C
      DIMENSION CF(NCF)
      FUNK=CF(1)
      IF(NCF.LE.1) RETURN
      DO 10 I=2,NCF
         IM1=I-1
         FUNK=FUNK+CF(I)*YVAL**IM1
   10 CONTINUE
      RETURN
      END
