      FUNCTION IVBGEN(NOLAYP)
C
C        DECIDES WHETHER A VECTOR BACKGROUND NEEDS TO BE GENERATED
C
C        IF IVBGEN=0, NO BACKGROUND
C                 =1, BACKGROUND REQUIRED
C
C           NOLAYP- NUMBER OF OVERLAY PLOTS DEFINED
C
C
      INCLUDE 'CEDRIC.INC'
c      PARAMETER (MXVSCT=20)
      PARAMETER (MAXLEV=61)
      COMMON /OVRLAY/ IOLAY,NPOLAY(5,MXVSCT),ICOLAY(10)
      COMMON /CONTUR/ CLB(MAXLEV,NFMAX),NLB(NFMAX),ICSPCS(10,NFMAX)
C
      K=0
      IF(NOLAYP.LE.0) GO TO 40
      DO 10 J=1,NOLAYP
         IV1=NPOLAY(1,J)
         IV2=NPOLAY(2,J)
         IF(IV1.LE.0.OR.IV2.LE.0) GO TO 10
         IF(ICSPCS(7,IV1).NE.0.OR.
     X      (NPOLAY(3,J).EQ.0.AND.ICSPCS(7,IV2).NE.0)) THEN
C
C           GENERATE BACKGROUND
C
            K=1
            GO TO 40
         END IF
   10 CONTINUE
   40 CONTINUE
      IVBGEN=K
      RETURN
      END
