      SUBROUTINE LSTSQR(M,N,X,Y,C,TX)
C     LEAST SQUARS POLYINOMIAL CURVE FIT (LSTSQR)  PAUL SWARZTRAUBER
C
C     DEFINITION OF INPUT PARAMETERS
C
C     M IS THE NUMBER OF COEFFICIENTS DESIRED
C     N IS THE NUMBER OF POINTS TO BE FITTED
C     X IS THE LOCATION OF THE INDEPENDENT VARIABLE TABLE
C     Y IS THE LOCATION OF THE    DEPENDENT VARIABLE TABLE
C     C IS THE LOCATION OF THE COMPUTED COEFFICIENTS
C     C(1) IS THE CONSTANT COEFFICIENT OF THE POLYNOMIAL
C     TX MUST BE DIMENSIONED AT LEAST N
C        AND IS A WORKSPACE ARRAY.
C
      DIMENSION A(20,20)
      DIMENSION C(10),X(1),Y(1),TX(1)
      IF(M.EQ.1)GO TO 60
      DO 20 I=1,N
20    TX(I)=1.0
      DO 30 J=1,M
      A(1,J)=0.
      C(J)=0.
      DO 30 I=1,N
      A(1,J)=A(1,J)+TX(I)
      C(J)=C(J)+TX(I)*Y(I)
30    TX(I)=TX(I)*X(I)
      DO 40 J=2,M
      A(J,M)=0.
      DO 40 I=1,N
      A(J,M)=A(J,M)+TX(I)
40    TX(I)=TX(I)*X(I)
      DO 50 I=2,M
      DO 50 J=2,M
50    A(I,J-1)=A(I-1,J)
      CALL EQSLV (M,1,A,C,D)
      RETURN
   60 CONTINUE
      SUM=0.0
      DO 65 I=1,N
      SUM=SUM+Y(I)
   65 CONTINUE
      C(1)=SUM/N
      C(2)=0.0
      RETURN
      END
