      SUBROUTINE MEDHST(MED,ITYP,NPPTS,HMIN,HINC)
C     
C     THIS SUBROUTINE CALCULATES THE MEDIAN FOR HISTOGRAM DISPLAYS
C     
      PARAMETER (MAXBIN=1003)
      COMMON /HSTBUF/ IBINS(MAXBIN),KBINS(MAXBIN)
      REAL MED

      IF (ITYP.EQ.1) THEN
C
C     FOR PLANE
C
         NPTSH=NPPTS/2
         ISUM=0
C
C     IBINS(MAXBIN) CONTAINS NUMBER OF VALUES LESS THAN LOWEST RANGE VALUE
C     CHOSEN BY USER
C
         ISUM=ISUM+IBINS(MAXBIN)
         IF (ISUM.GE.NPTSH) THEN
C
C     MEDIAN IS LESS THAN LOWEST RANGE VALUE CHOSEN BY USER
C
            MED=-999.0
            GOTO 250
         END IF
         DO 100 I=1,MAXBIN-1
            ISUM=ISUM + IBINS(I)
            IF (ISUM.GE.NPTSH) GOTO 120
 100     CONTINUE
C
C     MEDIAN IS GREATER THAN LOWEST RANGE VALUE CHOSEN BY USER
C
         MED=-999.0
         GOTO 250

 120     CONTINUE
         MED=HMIN+(I-1)*HINC

      ELSE IF (ITYP.EQ.2) THEN
C
C     FOR VOLUME
C
         NPTSH=NPPTS/2
         ISUM=0
         ISUM=ISUM+KBINS(MAXBIN)
         IF (ISUM.GE.NPTSH) THEN
            MED=-999.0
            GOTO 250
         END IF
         DO 200 I=1,MAXBIN-1
            ISUM=ISUM + KBINS(I)
            IF (ISUM.GE.NPTSH) GOTO 220
 200     CONTINUE
         MED=-999.0
         GOTO 250

 220     CONTINUE
         MED=HMIN+(I-1)*HINC

      END IF

 250  CONTINUE

      RETURN

      END

         


      
