      SUBROUTINE SETAXS(NCWORD,LF,LPR)
C
C        EXAMINES/SPECIFIES THE AXIS ORDERING FOR DISPLAY PURPOSES
C
      COMMON /AXUNTS/ IUNAXS,LABAXS(3,3),SCLAXS(3,3),AXNAM(3)
      CHARACTER*4 AXNAM
      
      DIMENSION NCWORD(3)
      CHARACTER*1 LF,LAX(3)
      READ(AXNAM(1),5)LAX(1)
      READ(AXNAM(2),5)LAX(2)
      READ(AXNAM(3),5)LAX(3)
 5    FORMAT(A1)
C
C        CALCULATE NEW AXIS CONFIGURATION
C
      I=IFINDC(LF,LAX,3,0)
      IF(I.LE.0) I=3
      LN=2**(I-1)
      LAD=LN+I-1
      DO 3 K=1,3
         NCWORD(K)=MOD(LAD,3)+1
         LAD=LAD+LN
    3 CONTINUE
      I1=NCWORD(1)
      I2=NCWORD(2)
      I3=NCWORD(3)
      WRITE(LPR,101)
  101 FORMAT(/' AXIS CONFIGURATION:',17X,'+')
      WRITE(LPR,102) AXNAM(I2)
  102 FORMAT(35X,A1,' +')
      WRITE(LPR,103) AXNAM(I3)
  103 FORMAT(23X,A1,' (FIXED)     +++')
      WRITE(LPR,104) AXNAM(I1)
  104 FORMAT(38X,A1/)
      RETURN
      END
