      SUBROUTINE SETBAD(IPR,KRD)
C
C        RESETS THE FLOATING POINT BAD DATA FLAG
C

      INCLUDE 'CEDRIC.INC'      
      COMMON /VOLUME/ INPID(NID),ID(NID),NAMF(4,NFMAX),SCLFLD(NFMAX),
     X                IRCP(NFMAX),MAPVID(NFMAX,2),CSP(3,3),NCX(3),
     X                NCXORD(3),NFL,NPLANE,BAD
      CHARACTER*2 NAMF
      CHARACTER*(*) KRD(10)
      DATA BAD/-1000.0/
      CHARACTER*1 CIBL
      DATA CIBL/' '/
      BAD= -1000.0
      IF(KRD(2).NE.CIBL) READ (KRD(2),101)BAD
  101 FORMAT(F8.0)
      WRITE(IPR,102) BAD
  102 FORMAT(8X,'BAD DATA WILL BE SET TO ',F12.3)
      RETURN
      END
