      SUBROUTINE WINDFD(KRD,IOPT)
C
C        SELECTS FIELDS IN EDIT FILE FOR DISPLAY DEPENDING ON THE
C           VALUE OF IOPT.
C           IF IOPT = 0, DECODE THE KRD IMAGE (USER DETERMINED)
C                   = 1, ALL ACTIVE FIELDS ARE DESIGNATED AS PRIMARY
C

      INCLUDE 'CEDRIC.INC'      
      COMMON /VOLUME/ INPID(NID),ID(NID),NAMF(4,NFMAX),SCLFLD(NFMAX),
     X                IRCP(NFMAX),MAPVID(NFMAX,2),CSP(3,3),NCX(3),
     X                NCXORD(3),NFL,NPLANE,BAD
      CHARACTER*2 NAMF
      COMMON /SETWND/ ISETW(2,3),PSETW(2,3),ISETFL(NFMAX)
      COMMON /UNITS/ LIN,LOUT,LPR,LSPOOL
      CHARACTER*8 IFLAD(NFMAX)
      CHARACTER*(*) KRD(10)
      CHARACTER*8 CTEMP,ITEST
      CHARACTER*10 IPSTAT(2)
      DATA IPSTAT/' PRIMARY',' SECONDARY'/
      CHARACTER*3 CIALL
      CHARACTER*1 CIBL,ISCND,IAD
      DATA ISCND,CIALL/'S','ALL'/
      DATA CIBL/' '/
      ISET=1
      IFLON=0
      IF(IOPT.NE.0) GO TO 10
C
C        DECODE CARD IMAGE AND SET FIELDS ACCORDING TO SPECIFICATIONS
C
         READ (KRD,101)IAD
C  101    FORMAT(8X,A1)
 101     FORMAT(/A1)
         IF(IAD.EQ.ISCND) ISET=2
         IFLON=0
         IF(KRD(3).EQ.CIALL.OR.KRD(3).EQ.CIBL) GO TO 10
         I1=3
    5    CONTINUE
C
C           EXPLICIT FIELD NAMES LOOP
C
            DO 8 I=I1,10
               IF(KRD(I).EQ.CIBL) GO TO 10
               IFLON=IFLON+1
 6             FORMAT(A8)
               IFLAD(IFLON)=KRD(I)
    8       CONTINUE
            I1=2
            CALL KARDIN(KRD)
            GO TO 5
   10    CONTINUE
C
C           SET FIELDS TO INDICATED CLASSIFICATION
C
         DO 20 I=1,NFMAX
            ISETFL(I)=0
            IF(NAMF(1,I).EQ.CIBL) GO TO 20
            ISETFL(I)=ISET
            IF(IFLON.EQ.0) GO TO 20
            WRITE (CTEMP,103)(NAMF(L,I),L=1,4)
            READ (CTEMP,500)ITEST
 500        FORMAT(A8)
  103       FORMAT(4A2)
            IGOT=IFINDC(ITEST,IFLAD,IFLON,0)
C
C              SET OPPOSITE IF NOT IN USER SUPPLIED LIST
C
               IF(IGOT.EQ.0) ISETFL(I)=3-ISET
C
   20    CONTINUE
C
C           PRODUCE A SUMMARY
C
         DO 40 J=1,2
            IFLON=0
            DO 25 I=1,NFMAX
               IF(ISETFL(I).NE.J) GO TO 25
               IFLON=IFLON+1
               WRITE (CTEMP,103)(NAMF(L,I),L=1,4)
               READ (CTEMP,500)IFLAD(IFLON)
   25       CONTINUE
            WRITE(LPR,104) IFLON,IPSTAT(J)
  104       FORMAT(/5X,I2,A10,' FIELDS EXIST ...')
            IF(IFLON.EQ.0) GO TO 40
            WRITE(LPR,105) (IFLAD(L),L=1,IFLON)
  105       FORMAT(18X,8A8)
   40    CONTINUE
      RETURN
      END
