      SUBROUTINE CONCHAR(STR1,NPLANE,STR2)
C
C     FILLS AN ARRAY OF CHARACTERS WITH A NEW CHARACTER
C
      CHARACTER*(*) STR1(NPLANE), STR2
      DO 10 I=1,NPLANE
         STR1(I)=STR2
 10   CONTINUE
      RETURN
      END
