      SUBROUTINE DIVZERO(VAL)
C
C     THIS SUBROUTINE JUST DIVIDES BY ZERO IN ORDER TO GENERATE A
C     TRACEBACK OF THE CALL STACK.
C
      IDIV=1/(1-INT(VAL))
      WRITE(*,*)'***IDIV=',IDIV

      RETURN

      END
