      SUBROUTINE DOSHFT(OBUF,RBUF,NX,NY,BAD,ISHIFT,JSHIFT)
C
C        DOES THE ACTUAL SHIFTING OF DATA
C
C        OBUF - THE INPUT BUFFER DIMENSIONED (NX,NY)
C        RBUF - THE OUTPUT BUFFER DIMENSIONED (NX,NY)
C        BAD - SET ALL BAD DATA TO BAD
C        ISHIFT - NUMBER OF POSITIONS TO SHIFT IN THE X DIRECTION
C        JSHIFT - NUMBER OF POSITIONS TO SHIFT IN THE Y DIRECTION
C
      DIMENSION OBUF(NX,NY),RBUF(NX,NY)
C
C
      NPLANE=NX*NY
      CALL CONFLD(RBUF,NPLANE,BAD)
C
      DO 150 J=1,NY
         JJ=J-JSHIFT
         IF (JJ.LT.1 .OR. JJ.GT.NY) GO TO 150
         DO 140 I=1,NX
            II=I-ISHIFT
            IF (II.LT.1 .OR. II.GT.NX) GO TO 140
            RBUF(I,J)=OBUF(II,JJ)
 140     CONTINUE
 150  CONTINUE
      RETURN
      END
