      SUBROUTINE EXPAND(KRD)
C
C        PROCESS EXPAND COMMAND
C           -CHILD OF KARDIN ROUTINE
C
      PARAMETER (MXCARD=10000,MXDEF=25,MXSUB=100,NREC=5)
      COMMON /DEFVAL/ KIMAGE(MXCARD),NAMBLK(MXDEF),LOCST(MXDEF)
     X               ,LENBLK(MXDEF),NDBLK,ISTORE,IXPAND(NREC)
     X               ,NXPAND(NREC),IX,IVSTAK(2,MXSUB),NSUB,ISFLG,ICFLG
      CHARACTER*8 KIMAGE,NAMBLK,IVSTAK
      CHARACTER*(*) KRD(10)
C
      IF (IX.EQ.NREC) THEN
         CALL CEDERX(549,1)
         RETURN
      END IF
      IX=IX+1
      DO 100 I=1,NDBLK
         IF (NAMBLK(I).EQ.KRD(2)) THEN
            NXPAND(IX)=I
            GOTO 110
         ENDIF
 100  CONTINUE
      CALL CEDERX(550,1)
      RETURN
 110  CONTINUE
      LOCN=NXPAND(IX)
      IXPAND(IX)=LOCST(LOCN)
      RETURN
      END
