c
c----------------------------------------------------------------------X
c
      INTEGER FUNCTION GETLEN (STRING)
C
C  DETERMINE THE LENGTH OF A CHARACTER STRING, EXCLUDING TRAILING BLANKS.
C     RETURNS LENGTH IN GETLEN
C
C     STRING - DECLARED AS CHARACTER IN CALLING ROUTINE
C     GETLEN -     "     "  INTEGER   "    "       "
C
      CHARACTER *(*) STRING
      CHARACTER*1 BLANK
      PARAMETER (BLANK=' ')
      INTEGER NEXT

C     START WITH THE LAST CHARACTER AND FIND THE FIRST NONBLANK
C
      DO 10 NEXT=LEN(STRING),1,-1
         IF(STRING(NEXT:NEXT).NE.BLANK)THEN
            GETLEN=NEXT
            RETURN
         END IF
   10 CONTINUE

C     ALL CHARACTERS ARE BLANKS
C
      GETLEN=0
      RETURN
      END
