      FUNCTION IGET16(IWD,IP)
C
C     THIS FUNCTION EXTRACTS 16 BIT INTEGERS THAT HAVE BEEN PACKED
C     INTO 32 BIT WORDS AND SIGN EXTENDS THEM INTO 32 BIT INTS
C
      INCLUDE 'CEDRIC.INC'
 
      IWRDSZ=WORDSZ
      NRESULT=ICEDSHFT(ICEDSHFT(IWD,IWRDSZ-(16*IP)),(16-IWRDSZ))
C      NRESULT=RSHIFT(LSHIFT(IWD,32-(16*IP)),16)
      IF(NRESULT.GT.32767)  NRESULT=NRESULT-65536
C
      IGET16=NRESULT
C
      RETURN
C
      END
