      SUBROUTINE SHOEDF(IDEV)
C
C        DISPLAYS THE CURRENT TABLE OF EDIT FIELDS
C

      INCLUDE 'CEDRIC.INC'      
      COMMON /VOLUME/ INPID(NID),ID(NID),NAMF(4,NFMAX),SCLFLD(NFMAX),
     X                IRCP(NFMAX),MAPVID(NFMAX,2),CSP(3,3),NCX(3),
     X                NCXORD(3),NFL,NPLANE,BAD
      CHARACTER*2 NAMF
      NF=ID(175)
      WRITE(IDEV,101) NF
  101 FORMAT(/1X,I2,' EDIT FIELDS EXIST AT PRESENT:')
      L1=176
      L2=175+5*NF
      WRITE(IDEV,102) (ID(L),ID(L+1),ID(L+2),ID(L+3), L=L1,L2,5)
  102 FORMAT((5X,8(1X,4A2)))
      RETURN
      END
