c
c----------------------------------------------------------------------X
c
      SUBROUTINE MYFRAME(NFRAME,NPLT,FYB,LABLS)
C
C  ANNOTATE MICROFILM WITH SHAVANO JOB NUMBER, DATE, TIME AND FRAME NUMBER
C  PLOT MAPPING: ASSUMES LAST CALL SET WAS TO FRACTIONAL COORDINATES
C     CALL SET(0.,1.,0.,1.,0.,1.,0.,1.,1)
C
      COMMON /PLTWIN/XRT(26),YTP(26),SIDEX(26),SIDEY(26),DXL,DXR,DYB,
     + DYT,NROW,NCOL,NWIN,IWIN,LABX(26),LABY(26),ILFLG,XBTP(26),
     + YBTP(26),SIZBX,XSHIFT,YSHIFT
      CHARACTER LABL*43,JOBNUM*8,LABLS*3
      CHARACTER*15 TODAY
      DATA FX/0.990/

c      FY=FYB-0.0925
      FY=0.01
      NFRAME=NFRAME+1

      IF(LABLS.EQ.'ABR'.OR.LABLS.EQ.'NON')GO TO 110

      CALL CDATE(TODAY)

      I=GETENV('QSUB_REQNAME',JOBNUM,1)
      WRITE(LABL,105)JOBNUM,TODAY(5:6),TODAY(7:8),TODAY(1:4),
     +     TODAY(9:10),TODAY(11:12),TODAY(13:14),NFRAME
 105  FORMAT(A8,'(',A2,'/',A2,'/',A4,'--',A2,':',A2,':',A2,
     +     ')--FRAME=',I5)
      CALL PLCHMQ(FX,FY,LABL,10.0,0.,1.)
  110 CALL FRAME
      NPLT=0
      RETURN
      END
