c
c----------------------------------------------------------------------X
c
      SUBROUTINE SAVVEC(INDAT,IFMT,SINDAT,NAMFLD,IFLD,NFLDS,NP,MXPLT)
C
C  STORE VECTOR PLOT CHARARACTERISTICS FOR LATER EXECUTION
C     INDAT  - INPUT ARRAY CONTAINING CHARACTERISTICS FOR ONE PLOT
C     SINDAT - OUTPUT ARRAY CONTAINING ALL (MXPLT) PLOT CHARACTERISTICS
C     NP     - NUMBER OF PLOTS TO BE DONE
C
C
      INCLUDE 'dim.inc'

      CHARACTER*8 INDAT(10),SINDAT(10,MXPLT)
      CHARACTER*8 NAMFLD(MXF),NAMU,NAMW,IFMT
      CHARACTER*4 NAMOUT
      DATA NAMOUT/'    '/
      DIMENSION IFLD(MXF)

      NP=NP+1
      IF(NP.GT.MXPLT)THEN
         WRITE(6,11)MXPLT
   11    FORMAT(1X,'*** MAXIMUM NUMBER OF PLOTS (',I3,') EXCEEDED ***')
         STOP
      END IF
      PRINT 55,(INDAT(I),I=2,10),NP
55    FORMAT(1X,' VECT: ',9A8,' NP=',I8)
      READ(INDAT,60)NAMU,NAMW
60    FORMAT(/A8/A8)
      DO 70 I=1,10
70    SINDAT(I,NP)=INDAT(I)
      CALL FIELD(NAMU,NAMFLD,NFLDS,NAMOUT)
      CALL FIELD(NAMW,NAMFLD,NFLDS,NAMOUT)
      RETURN
      END
