c
c----------------------------------------------------------------------X
c
      SUBROUTINE UNPCK(ID,N8,IPT,NGTS,IBEG,IEND,IRAY,AZ,EL)

C     ROUTINE TO DECOMPRESS HRD DATA.  DURING THE RECORDING PROCESS
C     STRINGS OF DATA AT OR BELOW THE NOISE POWER ARE REPLACED BY
C     TWO BYTES: A 0 BYTE FOLLOWED BY THE NUMBER OF GATES BELOW THE
C     NOISE POWER.  THIS ROUTINE EXTRACTS THAT INFORMATION FILLING
C     UP THE ENTIRE DATA ARRAY WITH DATA VALUES INCLUDING THE
C     ORIGINAL STRINGS OF 0'S.   THE FIRST BYTE OF A RAY HAS THE
C     VALUE 1 FOLLOWED BY AZIMUTH, ELEVATION AND TIME INFORMATION.
C     THE ACTUAL DBM INTEGER VALUES FOLLOW THE TIME.
C
C     IPT-  A POINTER THAT KEEPS TRACK OF WHICH BYTE  IS BEING
C           PROCESSED IN THE INPUT DATA BUFFER.

      DIMENSION ID(5000),IRAY(2024)

      IAZ=OR(256*ID(IPT+2),ID(IPT+1))
      IEL=OR(256*ID(IPT+4),ID(IPT+3))
      ISEC=OR(256*ID(IPT+7),ID(IPT+6))
      NUMZER=0
      AZ=IAZ*0.1
      EL=IEL*0.1
 30   FORMAT(1X,'IPT,AZ,EL,ISEC= ',I5,2F8.1,I6)
      IPT=IPT+8
      NG=1
 10   IF(ID(IPT).EQ.0)THEN
         NZERO=ID(IPT+1)
         NUMZER=NUMZER+NZERO
         IPT=IPT+2
         DO 20 I=NG,NG+NZERO-1
 20      IRAY(I)=0
         NG=NG+NZERO
      ELSE
         IRAY(NG)=ID(IPT)
         NG=NG+1
         IPT=IPT+1
      END IF
      IF(ID(IPT).NE.1.AND.IPT.LE.N8.AND.NG.LE.1500)GO TO 10
      RETURN
      END
