      FUNCTION CORR (N,X,Y,SE)
C
C        CALCULATES THE CORRELATION COOEFFICIENT OF A DATA SERIES
C
C
C         N- NUMBER OF DATA POINTS
C         X- ABCISSA VALUES
C         Y- ORDINATE VALUES
C        SE- STANDARD ERROR OF ESTIMATE
C
      DOUBLE PRECISION AMN1,AMN2,SUM1,SUM2,SUM3,SSQR1,SSQR2,
     X                 VAR1,VAR2
      DIMENSION X(1), Y(1)
      SUM1=0.0
      SUM2=0.0
      SUM3=0.0
      SSQR1=0.0
      SSQR2=0.0
      IF(N.LE.0) GO TO 50
      FN=1./N
      DO 40 I=1,N
         SUM1=SUM1+X(I)
         SUM2=SUM2+Y(I)
         SUM3=SUM3+X(I)*Y(I)
         SSQR1=SSQR1+X(I)*X(I)
         SSQR2=SSQR2+Y(I)*Y(I)
   40 CONTINUE
      IF(SSQR1.LE.0.0.OR.SSQR2.LE.0.0) GO TO 50
      AMN1=SUM1*FN
      AMN2=SUM2*FN
      VAR1=SSQR1*FN-(AMN1*AMN1)
      VAR2=SSQR2*FN-(AMN2*AMN2)
      IF (VAR1.LE.0.0 .OR. VAR2.LE.0.0) GOTO 50
      CORR=((SUM3*FN)-(AMN1*AMN2))/SQRT(VAR1*VAR2)
      IF ((VAR2*(1.0-CORR*CORR)).LT.0.0) GOTO 50
      SE=SQRT(VAR2*(1.0-CORR*CORR))
      RETURN
   50 CONTINUE
C
C        NO DATA- ERROR EXIT
C
      CORR=0.0
      SE=0.0
      RETURN
      END
