      SUBROUTINE DSFSTK(IDEV,ISTACK,IAUXSTCK,CONS,ISUM,MAXCON,NSTACK,
     X                  LFUN,MFUN,NFUN,ICONZ)
C
C        DISPLAYS THE CURRENT FUNCTION STACK.
C           IF ISUM=0, ENTIRE STACK WILL BE DISPLAYED
C                  >0, ISUM(TH) ENTRY WILL BE DISPLAYED
C
      PARAMETER (MXSTCK=30)
      DIMENSION IAUXSTCK(3,MXSTCK),CONS(MAXCON,MXSTCK)
      DIMENSION MFUN(NFUN),ICONZ(MXSTCK)
      CHARACTER LFUN(NFUN)*20,NAMFUN*20,IBL*1
      CHARACTER*2 ISTACK(15,MXSTCK),ITFL(3)
      DATA ITFL/ '/P', '/C', '/T' /
      DATA IBL/' '/
      IF(NSTACK.EQ.0) THEN
         WRITE(IDEV,103)
  103    FORMAT(' FUNCTION STACK IS CURRENTLY EMPTY.')
         RETURN
      ELSE
         IF(ISUM.EQ.0) THEN
            J1=1
            J2=NSTACK
            WRITE(IDEV,104)
  104       FORMAT(' FUNCTION STACK...')
         ELSE
            J1=ISUM
            J2=ISUM
         END IF
         WRITE(IDEV,105)
  105    FORMAT(' F (OUT)  TYPE',4X,'FUNCTION',6X,'F1',5X,'F2',
     X         13X,'C1',8X,'C2',8X,'C3',8X,'C4')
      END IF
      DO 5 J=J1,J2
         I1=IAUXSTCK(1,J)
         I2=IAUXSTCK(2,J)
         NC=MFUN(I2)
C
C        CENTER FUNCTION NAME ON LINE
C
      I=INDEX(LFUN(I2),IBL)-1
      L=(18-I)/2+1
      NAMFUN=IBL
      NAMFUN(L:L+I)=LFUN(I2)
      IF(ICONZ(J).EQ.0) THEN
         WRITE(IDEV,107) (ISTACK(I,J),I=1,4),ITFL(I1),NAMFUN,
     X                   (ISTACK(I,J),I=7,14),(CONS(I,J),I=1,NC)
  107    FORMAT(1X,5A2,1X,A18,1X,4A2,4A2,4F10.3)
      ELSE
         WRITE(IDEV,108) (ISTACK(I,J),I=1,4),ITFL(I1),NAMFUN,
     X                   (ISTACK(I,J),I=7,14)
  108    FORMAT(1X,5A2,1X,A18,1X,4A2,4A2,4X,
     X          'SPECIFIED FOR EACH LEVEL')
      END IF
    5 CONTINUE
      RETURN
      END
