      SUBROUTINE DSINIT(IP)
C
C        INITIALIZES DATA STRUCTURE CHARACTERISTICS FOR EDITING AND DISPLAY
C           IF IP=0, EVERY FIELD WILL BE INITIALIZED
C                >0, THAT FIELD NUMBER WILL BE INITIALIZED
C
      INCLUDE 'CEDRIC.INC'
      COMMON /VOLUME/ INPID(NID),ID(NID),NAMF(4,NFMAX),SCLFLD(NFMAX),
     X                IRCP(NFMAX),MAPVID(NFMAX,2),CSP(3,3),NCX(3),
     X                NCXORD(3),NFL,NPLANE,BAD
      CHARACTER*2 NAMF
      COMMON /SETWND/ ISETW(2,3),PSETW(2,3),ISETFL(NFMAX)
      COMMON /AXUNTS/ IUNAXS,LABAXS(3,3),SCLAXS(3,3),AXNAM(3)
      CHARACTER*4 AXNAM

      IF(IP.GT.0) GO TO 50
C
C        INITIALIZE ALL FIELDS
C
C FULL WINDOWING -ISETFL IS A DUMMY ARGUMENT
      CALL WINDIJ(ISETFL,1)
C DISPLAY STRUCTURES
      DO 20 I=1,NFMAX
         ISETFL(I)=0
         IF(I.GT.NFL) GO TO 20
         ISETFL(I)=1
   20 CONTINUE
      RETURN
   50 CONTINUE
C
C        SINGLE FIELD INITIALIZATION
C
C DISPLAY STRUCTURES
      ISETFL(IP)=0
      IF(SCLFLD(IP).NE.0.0) ISETFL(IP)=2
      RETURN
      END
