      SUBROUTINE HSTINT
C
C        ZEROES OUT THE HISTOGRAM TABLES
C
      PARAMETER (MAXBIN=1003)
      COMMON /HSTBUF/ IBINS(MAXBIN),KBINS(MAXBIN)
C
      CALL CONFLD(IBINS,MAXBIN,0)
      CALL CONFLD(KBINS,MAXBIN,0)
C
      RETURN
      END
