      SUBROUTINE IABPCK(IB,A,N,K,SF,BAD)
C
C        16-BIT PACKING ROUTINE
C           INPUT DATA IS ASSUMED TO BE IN THE RANGE +/-32768 WHEN SCALED
C
C       IB- OUTPUT BUFFER
C        A- INPUT ARRAY
C        N- NUMBER OF ELEMENTS
C        K- POSITION TO PACK INTO (R TO L)
C       SF- SCALING FACTOR REAL TO INTEGER
C      BAD- F.P. MISSING DATA VALUE
C
C
      DIMENSION IB(1),A(1)
      DATA PBAD/-32768./
      DATA MASK16/O'177777'/
C      DATA MASK16/177777B/

C
      IBS=16*(K-1)
      DO 10 I=1,N
         OUT=CVMGT(A(I)*SF,PBAD,A(I).NE.BAD)
         IOUT=OUT
         IOUT=ICEDAND(IOUT,MASK16)
         IB(I)=ICEDOR(IB(I),ICEDSHFT(IOUT,IBS))
C         IB(I)=OR(IB(I),LSHIFT(IOUT,IBS))
   10 CONTINUE
      RETURN
      END
