      FUNCTION LOCFLDID(IFLD,LTAB,N1,N2,LOOK)
C
C     LOCATES MATCHUPS BETWEEN QUANTITIES 
C           IFLD- ITEM BEING SEARCHED FOR
C           LTAB- SEARCH TABLE (***INT VAR CONTAINING CHARS***)
C             N1- NUMBER OF WORDS/ITEM
C             N2- NUMBER OF ITEMS IN THE TABLE
C           LOOK- NUMBER OF WORDS DEEP TO SEARCH FOR THE ITEM
      DIMENSION LTAB(N1,N2)
      CHARACTER*(*) IFLD(LOOK)
      CHARACTER*2 CTEMP

      IF (N2.LE.0) GO TO 15
      DO 10 M=1,N2    
      DO 5 L=1,LOOK
         WRITE(CTEMP,25)LTAB(L,M)
 25      FORMAT(A2)
         IF(IFLD(L).NE.CTEMP) GO TO 10
    5 CONTINUE
      K=M
      GO TO 20
   10 CONTINUE
   15 K=0
   20 CONTINUE
      LOCFLDID=K
      RETURN
      END
      
