      SUBROUTINE SELDEV(IDSEND,N,IDEST)
C
C        SELECTS EITHER THE PRINTER,DICOMED SPOOLER OR BOTH
C           DEPENDING UPON THE VALUE OF IDEST.
C
      COMMON /UNITS/ LIN,LOUT,LPR,LSPOOL
      CHARACTER*1 IDTAB(3),IDEST
      DIMENSION IDSEND(2)
      DATA IDTAB/'P','M','B'/
C
C        DEFAULT IS LINE PRINTER ONLY
C
      IDEV=IFINDC(IDEST,IDTAB,3,0)
      N=1
      IF(IDEV.NE.2) THEN
         IDSEND(N)=LPR
      ELSE
         IDSEND(N)=LSPOOL
      END IF
      IF(IDEV.EQ.3) THEN
         N=N+1
         IDSEND(N)=LSPOOL
      END IF
      RETURN
      END
