      SUBROUTINE OUTPCK(IBUF,LENGTH,IFLG)
C
C        PACK (OR NOT) DATA AND WRITE TO TAPE
C
C           IFLG=0 THEN PACK DATA
C                  ELSE NO PACKING DONE
C
      COMMON /UNITS/ LIN,LOUT,LPR,LSPOOL
      DIMENSION IBUF(LENGTH)
      DATA IBLK,IBIT,NBITS,NSKIP,MODE,NTYPE/800,0,16,0,1,2/
      LEN=LENGTH
      IF (IFLG.NE.0) GOTO 20
      CALL SBYTES(IBUF,IBUF,IBIT,NBITS,NSKIP,LEN)
      LEN=(LEN-1)/4 + 1
 20   CONTINUE
      IRP=(LEN-1)/IBLK + 1
      IAT=1
      DO 100 I=1,IRP
         LN=MIN0((LEN-(I-1)*IBLK),IBLK)
         CALL WRTAPE(LOUT,MODE,NTYPE,IBUF(IAT),LN)
         CALL IOWAIT(LOUT,NST,NWDS)
         IAT=IAT+LN
         IF (NST.EQ.0) GOTO 100
            CALL TAPMES(LOUT,NST)
            CALL CEDERX(535,1)
            CALL FLUSH_STDOUT
 100  CONTINUE
      RETURN
      END
