      SUBROUTINE CEDREAD(ID)
C
C     THIS SUBROUTINE READS IN A CEDRIC FORMAT DISK VOLUME AND
C     RETURNS ID HEADER INFORMATION ABOUT THE VOLUME AS WELL AS
C     THE DATA FOR THE VARIOUS FIELDS AND LEVELS IN THE VOLUME.
C
C     ID     -  510 WORD ID HEADER FOR VOLUME
C     ITEM   -  INTEGER SCRATCH ARRAY
C     RBUF   -  FLOAT ARRAY IN WHICH DATA VALUES FOR A GIVEN FIELD AND LEVEL
C               ARE RETURNED 
C     TBUF   -  FLOATING POINT SCRATCH ARRAY
C     ILHD   -  10 WORD LEVEL HEADER; USED FOR INTERNAL PROCESSING AND
C               NOT IMPORTANT TO UNDERSTAND
C     FLDNAM -  USED TO STORE NAME OF FIELDS. EACH FIELD NAME IS 
C               EIGHT CHARACTERS LONG 
C     IUN    -  UNIT NUMBER OF INPUT FILE; FILE SEARCHED FOR WILL BE
C               CALLED 'fort.iun'. 

C
      PARAMETER (NID=510)
      PARAMETER (MAXPLN=65536,MAXX=256,MAXY=256)
      DIMENSION ID(NID),ITEM(MAXPLN),RBUF(MAXX,MAXY),ILHD(10)
      DIMENSION TBUF(MAXPLN)
      CHARACTER*8 FLDNAM

C
C     READ FROM A FILE CALLED fort.10
C
      IUN=10
      LBF=NID
      LPR=6
C
C     DON'T REWIND; IF IREW=1, REWIND STREAM TO BEGINNING
C
      IREW=0
C
C     READ IN 16 BIT PACKED CARTESIAN HEADER; HEADER RETURNED INTO ID
C
      CALL CRTHIN(IUN,ID,LBF,NST,ITEM,IREW)
C
C     SUMMARIZE VOLUME INFORMATION
C
      CALL IMHSUM(LPR,ID)

C
C     PULL IN DATA FOR ALL FIELDS AND LEVELS NOW
C
      NX=ID(162)
      NY=ID(167)
      NZ=ID(172)
      NFLDS=ID(175)
      NPLIN=ID(162)*ID(167)
      BAD=-1000.0
      LASTLV=0
      LASTFD=0
      DO 150 KOT=1,NZ
         DO 140 LF=1,NFLDS
            INF=171+(5*LF)
            WRITE(FLDNAM,113)ID(INF),ID(INF+1),ID(INF+2),ID(INF+3)
 113        FORMAT(4A2)

C
C     THE FOLLOWING FUNCTION RETURNS THE DATA FOR LEVEL KOT AND
C     FIELD LF IN ARRAY TBUF
C
            CALL FETCHZ(IUN,TBUF,ITEM,NPLIN,LASTLV,LASTFD,KOT,ZLEV,
     X                  FLDNAM,BAD,ID,ILHD)

            DO J=1,NY
               DO I=1,NX
                  IND=I + (J-1)*NX
                  RBUF(I,J)=TBUF(IND)
               END DO
            END DO

C
C     USER MUST SUPPLY THE SUBROUTINE FOR THIS NEXT CALL.
C     ESSENTIALLY, IT MUST BE ABLE TO STORE THE DATA FOR Z-LEVEL KOT
C     AND FIELD LF INTO WHATEVER INTERNAL STRUCTURES YOU HAVE.
C

            CALL PLACEPLANE(RBUF,LF,KOT,FLDNAM,NX,NY)
 140     CONTINUE
 150  CONTINUE


      CALL CSKPVOL(IUN,1,NST)
      RETURN

      END
