      SUBROUTINE BACKREC(IUN,NRECS)
C
C     BACKS UP NRECS RECORDS ON THE INTERNAL FILE. THIS IS USED
C     TO DISCARD A SWEEP AFTER THE RECORDS HAVE ALREADY BEEN
C     WRITTEN.
C
      DO I=1,NRECS
         BACKSPACE (IUN,ERR=100)
      END DO

      RETURN

 100  WRITE(*,20)
 20   FORMAT(/,5X,'+++LOW LEVEL I/O ERROR IN BACKREC+++')
      STOP

      END
