      SUBROUTINE FXTABLE(KRD)
C
C     THIS SUBROUTINE READS IN A LIST OF SWEEP NUMBERS TO ACCEPT OR
C     SKIP. THIS LIST IS MADE ACTIVE WITH P10 ON THE PROCESS CARD.
C
      CHARACTER*8 KRD(10), OPTION, FWORD
      PARAMETER (MAXSKP=27)
      COMMON /FXTABL/ IFXTAB,ISKIP,IACCPT,FTABLE(MAXSKP),ITRAN
      

C
C     INITALIZE SOME VALUES
C
      ISKIP=0
      IACCPT=0
      DO 75 I=1,MAXSKP
         FTABLE(I)=0.0
 75   CONTINUE
C
C     PARSE THE COMMAND CARD
C
      READ(KRD,100)OPTION
 100  FORMAT(/A8)
      IF (OPTION.EQ.'SKIP') THEN
         ISKIP=1
      ELSE IF (OPTION.EQ.'ACCEPT') THEN
         IACCPT=1
      END IF

C
C     READ IN ALL THE SWEEP VALUES
C
      ICUR=1
      ILIN=1
 125  CONTINUE
      CALL KARDIN(KRD)
      READ (KRD,150)FWORD
 150  FORMAT(A8)
      IF (FWORD.EQ.'END') GOTO 300
      IF (ILIN.GE.4) THEN
         WRITE(*,*)'***ERROR: ONLY 27 ENTRIES (3 LINES) PERMITTED',
     X             '  IN TABLE OF SWEEP VALUES***'
         STOP
      END IF

      READ (KRD,200)FTABLE(ICUR),FTABLE(ICUR+1),FTABLE(ICUR+2),
     X     FTABLE(ICUR+3),FTABLE(ICUR+4),FTABLE(ICUR+5),
     X     FTABLE(ICUR+6),FTABLE(ICUR+7),FTABLE(ICUR+8)
 200  FORMAT(/F8.0/F8.0/F8.0/F8.0/F8.0/F8.0/F8.0/F8.0/F8.0)
      
      DO 175 I=0,8
         IF (FTABLE(ICUR+I).EQ.0.0) THEN
            ICUR=ICUR+I+1
            ILIN=ILIN+1
            GOTO 125
         END IF
 175  CONTINUE
      ICUR=ICUR+9
      ILIN=ILIN+1
      IF (ICUR.GT.28) THEN
         WRITE(*,*)'***ERROR: ONLY 27 ENTRIES PERMITTED IN TABLE OF',
     X             ' SWEEP VALUES***'
         STOP
      END IF
      GOTO 125

 300  CONTINUE
      
      WRITE(*,350)
 350  FORMAT(//5X,'SUMMARY OF FXTABLE COMMAND ')
      WRITE(*,375)
 375  FORMAT(5X,'------- -- ------- -------')
      WRITE(*,400)OPTION
 400  FORMAT(/5X,'                       TABLE OPTION: ',A8,
     X       ' SPECIFIED SWEEP NUMBERS' /)
      RETURN
      END

      
