      SUBROUTINE IGET8(IWRD,INDX,IVAL)
C
C     EXTRACT AN 8 BIT QUANTITY FROM A NORMAL WORD
C

      CALL GBYTES(IWRD,IVAL,((INDX-1)*8),8,0,1)

      IF (IVAL.GT.127) IVAL=IVAL-256
      RETURN

      END

