      SUBROUTINE MTHSUM(IDEV,ICC,IYES)

      INCLUDE 'SPRINT.INC'
c-----PARAMETER (MAXFLD=16)
c-----DATA IBAD/-32768/

      LOGICAL IS360

      COMMON/ADJUST/INFLD(MAXFLD,3),SCLIF(MAXFLD,2),NIF,IOFLD(MAXFLD,3),
     X     SCLOF(MAXFLD,2),NOF,SCLAZ,SCLRNG,SCLEL,UNSCAZ,UNSCRG,UNSCEL,
     X     LOWAZ,IZAD,IS360,MINAZ,MAXAZ,METSPC(MAXFLD),IWFLD(MAXFLD),
     X     NFLI,SCLNYQ,UNSNYQ

      COMMON /CFLD/NFLDS
      COMMON /CFLDC/ IFIELD(MAXFLD), INTINF(MAXFLD,3)
      CHARACTER*8 INTINF,IFIELD

      COMMON /FNAMES/ CINFLD(MAXFLD),CIOFLD(MAXFLD)
      CHARACTER*8 CINFLD, CIOFLD

      COMMON /NCARFB/ NF,IDXFV(MAXFLD)
      DIMENSION GCOEF(2)
      EQUIVALENCE (METSPC(1),METH)
      CHARACTER*1 ICC,IYES
      CHARACTER*8 MEDA(6,2),MRSM(3,2),ITPTAB(11),IYTERP(4),IFLA(2)
      CHARACTER*8 IFOLD(2),INYP,IBL,INTERP,IFTNAM,IFLP
      DATA MEDA/'BILINEAR',' INTERPO','LATION ',' ',' ',' ',
     X          'CLOSEST ','POINT WI','THIN A S','PECIFIED',
     X          ' DISTANC','E'/
      DATA MRSM/'WITH RAN','GE SMOOT','HING','WITH NO ','SMOOTHIN','G'/
      DATA ITPTAB/'UNKNOWN ','PWR-DBM ','REFLECT ','VELOCITY',
     X            'STD DEV ','COH-PWR ','TIME-SEC','GEOMETRY',
     X            '        ','        ','        '/
      DATA IYTERP /'AS IS','NO','DECIMATE','LINEAR'/
      DATA IFLA /'DIRECT','DERIVED'/
      DATA IFOLD/'FOLDED','UNFOLDED'/
      DATA IBL /' '/

      IF (IYES .NE. 'Y') RETURN
      WRITE (IDEV,100) ICC
 100  FORMAT(A1)
      IRSM=1
      IF(METSPC(2).EQ.0) IRSM=2
      IF(METH.EQ.1) THEN
         MEDA(4,1)=MRSM(1,IRSM)
         MEDA(5,1)=MRSM(2,IRSM)
         MEDA(6,1)=MRSM(3,IRSM)
      END IF
      WRITE(IDEV,105) (MEDA(I,METH), I=1,6)
 105  FORMAT(' INTERPOLATION METHOD SUMMARY'//3X,'METHOD: ',6A8)
      WRITE(IDEV,106)NIF,NOF,NFLI
 106  FORMAT(3X,'METHOD: # input, output, and interpolated fields ',
     +     'NIF,NOF,NFLI=',3I6)
      WRITE(IDEV,110)
 110  FORMAT(/3X,'INPUT FIELDS'/4X,'NO.',3X,'NAME',9X,'SCALE FACTOR',
     +     5X,'INTERPOLATE',5X,'FIELD TYPE')
      IBIG=IABS(IBAD)*2
      DO 10 I= 1,NIF
         INYP=IBL
         INTERP=IYTERP(2)
         J=ITPFLDC(CINFLD(I))
         IFTNAM=ITPTAB(J+1)
         IFTYP=INFLD(I,2)
         IF (IFTYP .LT. 0) GO TO 4
         INTERP=IYTERP(1)
         IFTNAM=ITPTAB(IFTYP+1)
         IF(NF.EQ.0) GO TO 4
         DO 3 J=1,NF
            K=IDXFV(J)
            IF(I.NE.K) GO TO 3
            INTERP=IYTERP(3)
            GO TO 4
 3       CONTINUE
 4       CONTINUE
         IF(INFLD(I,3).NE.0.AND.IABS(INFLD(I,3)).LT.IBIG
     X        .AND.IFTYP.EQ.3) INYP=IFOLD(1)
         IF(INFLD(I,3).NE.0.AND.(IFTYP.EQ.1.OR.IFTYP.EQ.2))
     X        INTERP=IYTERP(4)
         WRITE(IDEV,125) I,CINFLD(I),SCLIF(I,1),INTERP,IFTNAM,INYP
 10   CONTINUE
      WRITE(IDEV,120)
 120  FORMAT(/3X,'OUTPUT FIELDS'/4X,'NO.',3X,'NAME',9X,'SCALE FACTOR',
     +     5X,'INTERPOLATION',3X,'FIELD TYPE')
      VNYQ=0.0
      DO 40 I=1,NOF
         IFTYP=ITPFLDC(CIOFLD(I))
         IFTNAM=ITPTAB(IFTYP+1)
         INYP=IBL
         IFLP=IFLA(1)
         IF(IOFLD(I,2).EQ.0) GO TO 30
         IF (IOFLD(I,2) .LT. 0) IFLP=IFLA(2)
         K=IABS(IOFLD(I,2))
         J=IWFLD(K)
         IF (J.LE.0) GOTO 30
         IF(INFLD(J,3).EQ.0.OR.IABS(INFLD(J,3)).GE.IBIG
     X        .OR.INFLD(J,2).NE.3) GO TO 30
         INYP=IFOLD(2)
         IF(VNYQ.EQ.0.0) VNYQ=INFLD(J,3)*SCLIF(J,2)+0.005
 30      CONTINUE
         WRITE(IDEV,125) I,CIOFLD(I),SCLOF(I,1),IFLP,IFTNAM,INYP
 125     FORMAT(4X,I2,4X,A8,8X,F6.1,11X,A8,7X,A8,4X,A8)
 40   CONTINUE
      IF(METH.EQ.1.AND.METSPC(2).NE.0) THEN
         WRITE(IDEV,130) METSPC(2),METSPC(3)
 130     FORMAT(/3X,'RANGE SMOOTHING:'/4X,I3,' NOMINAL GATE AVERAGE',
     X        '  (',I2,' MINIMUM)')
         IF(METSPC(7).NE.0) THEN
            GCOEF(1)=METSPC(7)*0.001
            GCOEF(2)=METSPC(8)*0.001
            WRITE(IDEV,131) GCOEF,METSPC(9)
 131        FORMAT(4X,'COMPUTED NO. OF GATES TO AVERAGE: ',F8.3,
     X           ' * RANGE (KM) ',SP,F8.3,S,
     X           /26X,'TO  ACCEPT: ',I3,' FEWER')
         END IF
      END IF
      RMAX=METSPC(4)*SCLRNG
      WRITE(IDEV,135) RMAX
 135  FORMAT(3X,'MAXIMUM ACCEPTABLE DISTANCE FOR A CLOSEST POINT',
     X     ' ESTIMATE TO BE KEPT:',F7.2,' KM.')
      IF(VNYQ.NE.0.0) WRITE(IDEV,140) VNYQ
 140  FORMAT(/3X,'VOLUME NYQUIST VELOCITY:',F7.2,' M/S.')
      RETURN
      END
