      SUBROUTINE SKIPVOL(NWCT,MBYTE,NST,SWAPPING)
C
C     THIS SUBROUTINE SKIPS A LOGICAL VOLUME SCAN ON RP-7 FIELD
C     FORMAT TAPES BY READING RAYS UNTIL EOF IS ENCOUNTERED.
C
      DO 100 I=1,1000000
         CALL NWRAY(NWCT,MBYTE,NST,SWAPPING)
         IF (NST.NE.0) RETURN
 100  CONTINUE
      WRITE(*,*)'***ERROR SKIPPING VOLUME IN SKIPVOL***'
      STOP

      END
