#! /bin/sh
#
# Run ced_examp and compare the output to the baseline.

diff="../../tests/diff_cedric"
if [ -x ../../source/gcedric ]; then
    ./run_ced_examp ../../source/gcedric  >& ced_examp-latest.out
    $diff ced_examp.out ced_examp-latest.out
fi

./run_ced_examp ../../source/cedric  >& ced_examp-cedric-latest.out
$diff ced_examp-cedric.out ced_examp-cedric-latest.out
