#! /bin/sh -x

export AUTOMAKE='automake --foreign --add-missing --force-missing --copy'
exec autoreconf

#autoheader
#aclocal --output=config/aclocal.m4
#autoconf --force -I config
#automake --foreign --add-missing --force-missing --copy
