C
C     THE FUNCTIONS IN THIS SUBROUTINE ISOLATE THE REST OF THE CEDRIC
C     CODE FROM MACHINE DIFFERENCES IN FORTRAN LOGICAL FUNCTIONS.
C     (WORKS ON HP)
C
      FUNCTION AND(I1,I2)
C
C     SUBROUTINE TO PERFORM A LOGICAL AND. 
C
      AND = IAND(I1,I2)
      RETURN
      END

      FUNCTION OR(I1,I2)
C
C     PERFORM A LOGICAL OR
C
      OR = IOR(I1,I2)
      RETURN
      END

      FUNCTION SHFT(I1,I2)
C
C     SHIFT I1 I2 PLACES TO THE LEFT IF I2 >0, TO THE RIGHT IF I2 < 0
C
      SHFT = ISHFT(I1,I2)
      RETURN
      END

      FUNCTION XOR(I1,I2)
C
C     EXCLUSIVE OR OF I1,I2
C
      XOR = IXOR(I1,I2)
      RETURN
      END

      
