      SUBROUTINE COMMNT(IPR,KRD)
C
C        SENDS USER SUPPLIED COMMENTS TO THE PRINT FILE
C
      PARAMETER (MXCARD=10000,MXDEF=25,MXSUB=100,NREC=5)
      COMMON /DEFVAL/ KIMAGE(MXCARD),NAMBLK(MXDEF),LOCST(MXDEF),
     X                LENBLK(MXDEF),NDBLK,ISTORE,IXPAND(NREC),
     X                NXPAND(NREC),IX,IVSTAK(2,MXSUB),NSUB,ISFLG,ICFLG
      CHARACTER*8 KIMAGE,NAMBLK,IVSTAK
      DIMENSION IDSEND(2)
      CHARACTER*(*) KRD(10)
      CHARACTER*1 IDEST
      CHARACTER*3 ITST1,ITST2,ICOM,IEND
      DATA ICOM,IEND/'COM','END'/
C
C        DETERMINE DEVICE(S) FOR TRANSMISSION OF COMMENTS
C
      READ (KRD(2),100)IDEST
  100 FORMAT(A1)
      CALL SELDEV(IDSEND,N,IDEST)
      DO 5 I=1,N
         IDEV=IDSEND(I)
         WRITE(IDEV,201)
  201    FORMAT(/)
    5 CONTINUE
      ICFLG=1
C
C        SEND COMMENTS TO OUTPUT
C
      NEST=1
   10 CONTINUE
      CALL KARDIN(KRD)
      READ (KRD(1),101)ITST1,ITST2
  101 FORMAT(2A3)
      IF(ITST1.EQ.ICOM) THEN
         IF(ITST2.NE.IEND) NEST=NEST+1
         IF(ITST2.EQ.IEND) NEST=NEST-1
      END IF
      DO 15 I=1,N
         IDEV=IDSEND(I)
      IF(IDEV.EQ.IPR) GO TO 15
         WRITE(IDEV,202) KRD
  202    FORMAT(1X,10A8)
   15 CONTINUE
      IF(NEST.GT.0) GO TO 10
      DO 20 I=1,N
         IDEV=IDSEND(I)
         WRITE(IDEV,201)
   20 CONTINUE
      ICFLG=0
      RETURN
      END
