      SUBROUTINE DSPCOD(KRD,IBUF,RBUF,IPR)
C
C     PRODUCES A CODED DISPLAY OF CARTESIAN DATA
C
      INCLUDE 'CEDRIC.INC'
      PARAMETER (NDSYM=27)
      COMMON /VOLUME/ INPID(NID),ID(NID),NAMF(4,NFMAX),SCLFLD(NFMAX),
     X                IRCP(NFMAX),MAPVID(NFMAX,2),CSP(3,3),NCX(3),
     X                NCXORD(3),NFL,NPLANE,BAD
      CHARACTER*2 NAMF,NAME(4)
      COMMON /DSPECS/ IWIND(2,3),PWIND(2,3),NCWORD(3),IFLDW(NFMAX),
     X                SCLFAC(NFMAX),NSYMCD(2,NFMAX),WIDCD(NFMAX),
     X                ZREFCD(NFMAX),THKLIN(NFMAX)
      DIMENSION IBUF(1),RBUF(1),MAXSYM(2),IDSEND(2)
      CHARACTER*(*) KRD(10)
      COMMON /SYMTAB/ ISYM(NDSYM,2)
      CHARACTER*1 ISYM,IDEST,LF,IWOP
      CHARACTER*3 ITEST
      CHARACTER*8 NAMIN
      DATA MAXSYM/ 26, 26/
C
C     INITIALIZE CODED DISPLAY PARAMETERIZATION
C
      READ (KRD,100)IDEST,LF,RSKP,IWOP
C  100 FORMAT(8X,A1,7X,A1,7X,F8.0,40X,A1)
 100  FORMAT(/A1/A1/F8.0//////A1)
      LSKP=MAX1(RSKP,1.0)
      CALL WINSET(IWIND,PWIND,IWOP)
      CALL SETAXS(NCWORD,LF,IPR)
      CALL SELDEV(IDSEND,N,IDEST)
C     
C     ESTABLISH FIELDS, SCALE FACTORS AND DISTRIBUTION TABLES
C
      CALL CONFLD(IFLDW,NFMAX,0)
 10   CONTINUE
C
C     READ ANOTHER FIELD CARD
C
      CALL KARDIN(KRD)
      CALL COMCHK(IPR,KRD)
      READ (KRD,101)ITEST,NAMIN,SCL
C 101  FORMAT(A3,5X,A8,F8.0)
 101  FORMAT(A3/A8/F8.0)
      IF(ITEST.EQ.'END') GO TO 20
      IF(SCL.EQ.0.0) SCL=1.0
      CALL FLDSET(NAMIN,NAMF,IFLDW,1,NST)
      IF(NST.NE.0) GO TO 10
      CALL FLDSETR(NAMIN,NAMF,SCLFAC,SCL,NST)
C
C     ESTABLISH DISTRIBUTION TABLE
C
      CALL SETDCD(1,IDSEND,N,NAMF,ISYM,NDSYM,MAXSYM,KRD,NST)
      GO TO 10
 20   CONTINUE
C
C     GENERATE DISPLAYS AND SEND THEM TO THE APPROPRIATE DEVICES
C
      CALL PLNFLD(IFIXAX,L1,L2,NFDSP)
      print *,'DSPCOD: ifixax,ncword=',ifixax,ncword
      IF(NFDSP.EQ.0) GO TO 91
      DO 86 L=L1,L2,LSKP
         JFLD=0
         DO 85 I=1,NFDSP
 81         CONTINUE
C
C     SEARCH FOR NEXT ACTIVE DISPLAY FIELD
C
            JFLD=JFLD+1
            IV=MAPVID(JFLD,2)
            IF(IFLDW(IV).EQ.0) GO TO 81
            CALL NEXACT(IFIXAX,L,IV,RLEV,NAME,1)
            print *,'DSPCOD: ifixax=',ifixax
            CALL FETCHD(IN,ID,L,JFLD,IBUF,RBUF,N1,N2,
     X           IFIXAX,BAD,RLEV,NST)
            print *,'DSPCOD: ifixax=',ifixax
            DO 84 M=1,N
               CALL CODER(IDSEND(M),RBUF,N1,N2,BAD,IWIND,PWIND,
     X              SCLFAC(IV),
     X              ISYM,NSYMCD(1,IV),WIDCD(IV),ZREFCD(IV),
     X              NCWORD,RLEV,NAME)
 84         CONTINUE
 85      CONTINUE
 86   CONTINUE
 90   CONTINUE
      RETURN
 91   CONTINUE
      CALL CEDERX(539,0)
      RETURN
      END
