      SUBROUTINE HSTLST (IUN,BEG,END,STP,SCALE,ILHOP)
C
C        LISTS HISTOGRAMS OUT TO UNIT IUN
C
C        ILHOP- SUMMARY SWITCH =0 RESULTS FROM LAST PLANE
C                       OTHERWISE SUMMARIZE ACCUMULATED INFO.
C
      COMMON /HSTBUF/ IBINS(60),KBINS(60)
      DIMENSION PC(60)
      CHARACTER IBUF*129,KENCD*20
C
      NBINS=(END-BEG)/STP+3.00001
      INDEX=NBINS-1
C
      IF(ILHOP.NE.0) THEN
         CALL COPIX(IBINS,KBINS,60)
      END IF
C
      ISUM=0
      DO 150 I=1,INDEX
         ISUM=ISUM+IBINS(I)
         PC(I)=0.0
 150  CONTINUE
      MAX=0
      IF (ISUM.NE.0) THEN
         SUMHI=100./FLOAT(ISUM)
         DO 200 I=1,INDEX
            PC(I)=IBINS(I)*SUMHI
            ITEST=NINT(PC(I))
            MAX=MAX0(ITEST,MAX)
 200     CONTINUE
         ENDIF
C
C        ANY HEADER GOES HERE
C
      WRITE (IUN,201) SCALE,IBINS(NBINS)
      ILINE=1
 201  FORMAT (6X,'HISTOGRAM     (SCALED BY',F7.2,')',I9,' BAD POINTS')
      CALL HMARKS(MAX,PC(1),IBUF,LIM)
      WRITE (KENCD,202)BEG
 202  FORMAT (' (   -   ,',F7.2,'): ')
      IBUF(1:20)=KENCD(1:20)
      WRITE (IUN,203) IBUF
      ILINE=ILINE+1
 203  FORMAT (A)
      IBIN=1
      ALAST=BEG
      SECT=BEG+STP
 250  CONTINUE
C
C        LOOP FOR EACH HISTOGRAM INTERVAL
C
         IBIN=IBIN+1
         IF (IBIN.GE.INDEX) GOTO 300
         CALL HMARKS(MAX,PC(IBIN),IBUF,LIM)
         WRITE (KENCD,211)ALAST,SECT
 211     FORMAT (' (',F7.2,',',F7.2,'): ')
         IBUF(1:20)=KENCD(1:20)
         WRITE (IUN,203) IBUF
         ILINE=ILINE+1
         ALAST=SECT
         SECT=SECT+STP
         GOTO 250
 300  CONTINUE
      CALL HMARKS(MAX,PC(IBIN),IBUF,LIM)
      WRITE (KENCD,301)ALAST
 301  FORMAT (' (',F7.2,',   +   ): ')
      IBUF(1:20)=KENCD(1:20)
      WRITE (IUN,203) IBUF
      CALL HDUMP(MAX,IUN)
      RETURN
      END
