      SUBROUTINE NEXACT(IFIXAX,LEV,IVFL,RLEV,NAME,NFP)
C
C        INITIALIZE FIELD NAMES AND LEVEL HEIGHT
C
C
      INCLUDE 'CEDRIC.INC'
      COMMON /VOLUME/ INPID(NID),ID(NID),NAMF(4,NFMAX),SCLFLD(NFMAX),
     X                IRCP(NFMAX),MAPVID(NFMAX,2),CSP(3,3),NCX(3),
     X                NCXORD(3),NFL,NPLANE,BAD
      CHARACTER*2 NAMF,NAME(4,NFP),NONE(4)
      COMMON /AXUNTS/ IUNAXS,LABAXS(3,3),SCLAXS(3,3),AXNAM(3)
      CHARACTER*4 AXNAM
      DIMENSION IVFL(NFP)
      DATA NONE/'NO','NE',' Y','ET'/
C
C        CALCULATE LEVEL IN SPATIAL UNITS AND DETERMINE FIELD NAMES
C                  TO BE DISPLAYED
C
      RLEV=CSP(1,IFIXAX)+(LEV-1)*CSP(3,IFIXAX)
      RLEV=RLEV*SCLAXS(IFIXAX,IUNAXS)
      DO 5 L=1,NFP
         J=IVFL(L)
         IF(J.EQ.0) THEN
            CALL COPCX(NAME(1,L),NONE,4)
         ELSE
            CALL COPCX(NAME(1,L),NAMF(1,J),4)
         END IF
    5 CONTINUE
      RETURN
      END
