      SUBROUTINE REGINT(NAMX,NAMY,IFIXAX,LCAX,IPR)
C
C        WRITES OUT A HEADER LINE FOR THE REGRESSION STATS
C
      CHARACTER*2 NAMX(4),NAMY(4)
      COMMON /AXUNTS/ IUNAXS,LABAXS(3,3),SCLAXS(3,3),AXNAM(3)
      CHARACTER*4 AXNAM,LCAX
C
      WRITE(IPR,201) LCAX,LABAXS(IFIXAX,IUNAXS),NAMX,NAMY
  201 FORMAT(2X,A2,' ',A4,11X,4A2,'-IND',5X,4A2,'-DEP',5X,'LINEAR',
     X       ' RELATIONSHIP'/14X,'N     MEAN    STDV     MEAN    STDV',
     X       '  CORR  STDERR      C0      C1')
C
      RETURN
      END
