      SUBROUTINE STATZI
C
C        ZEROES OUT STATISTICAL ACCUMULATORS
C
C
      COMMON /STATBF/ NV,IV1,IV2,JV1,JV2,FVMN,FVMX
      COMMON /STATBF2/ FACV,FSQV
      DOUBLE PRECISION FACC,FSQR
      DOUBLE PRECISION FACV,FSQV
C
      NV=0
      IV1=100000
      IV2=0
      JV1=100000
      JV2=0
      FACV=0.0
      FSQV=0.0
      FVMN=1.E8
      FVMX= -FVMN
C
      RETURN
      END
