      BLOCK DATA

      INCLUDE 'SPRINT.INC'
c-----PARAMETER (MAXFLD=16)
      COMMON /CINP/IUN,ISKP,ORLAT,ORLON
      COMMON /CINPC/ NMRAD,ITAP,TAPE_UNIT
      CHARACTER*4 NMRAD
      CHARACTER*8 ITAP
      CHARACTER*8 TAPE_UNIT
      DATA ITAP/'-9999'/
      
      COMMON /UNITS/LUN,LSKP,FEETS
      COMMON /UNITSC/ IPROJ,LTAP,ISCI
      CHARACTER*4 IPROJ
      CHARACTER*8 LTAP,ISCI
      DATA LTAP,ISCI/'-9999','-9999'/

      COMMON /SETAZM/ USAZ1,USAZ2,USGAP,USINC,IFOR36,IFORDR
      DATA            USAZ1,USAZ2,USGAP,USINC,IFOR36,IFORDR/
     X                  0.0,  0.0,  0.0,  0.0,     0,     0/

      COMMON /TRANS/ X1,X2,XD,Y1,Y2,YD,Z1,Z2,ZD,NX,NY,NZ,XORG,YORG,
     X     ANGXAX,ZRAD,AZLOW,BAD,ASNF,ACSF,IAXORD(3),NPLANE,EDIAM
      DATA IAXORD/1,2,3/

      COMMON /AXUNIT/ IFIXAX,IUNAXS,LABAXS(3,3),SCLAXS(3,3),AXNAM(3),
     X     ORDER_LABL
      CHARACTER*8 AXNAM
      CHARACTER*11 ORDER_LABL
      DATA SCLAXS/1.0,1.0,1.0, 0.5399568035,0.5399568035,3.280833,
     X                         0.6213688756,0.6213688756,3.280833/

      COMMON /CPRO/KDAY,KBTIM,KETIM,IROV,ISWMTH,FXSTOL
      COMMON /CPROC/ IREORD(3)
      CHARACTER*1 IREORD
      DATA IREORD/'N','N','Y'/

      COMMON /CFLD/NFLDS
      COMMON /CFLDC/ IFIELD(MAXFLD), INTINF(MAXFLD,3)
      CHARACTER*8 INTINF,IFIELD
      DATA NFLDS/-9999/

      COMMON /FORMAT/ IRP,IBLOCK
      DATA IRP /0/

      COMMON /CRNG/ELTUS,MNBEM,RUSR1,RUSR2,RG1,RG2,DRG,NRG,VNYQ,
     X     RNOTUS,DRGUS,CFAC1,CFAC2,CFAC3
      COMMON /CRNGC/ IRCFXL
      CHARACTER*8 IRCFXL
      DATA ELTUS,RUSR1,RUSR2,CFAC1,CFAC2,CFAC3,VNYQ,RNOTUS,DRGUS
     X     /360.0,8*0.0/
      DATA MNBEM,IRCFXL/2, ' '/

      END
