      SUBROUTINE CHKMSG(NST,KRAY)
C
C        PRINT ERRORS -- TERMINATE
C
      INCLUDE 'SPRINT.INC'

      GOTO (10,20,30,40,50,60,70,80,90)NST
      STOP 71100

 10   CONTINUE
      PRINT 102,KRAY
 102  FORMAT (5X,'***MORE THAN 4 RECORDS PER RAY -- RAY ',I5)
      STOP

 20   CONTINUE
      PRINT 23,KRAY
 23   FORMAT (5X,'***CHANGE IN FIRST GATE -- RAY ',I5)
      STOP

 30   CONTINUE
      PRINT 33,KRAY
 33   FORMAT (5X,'***CHANGE IN GATE SPACING -- RAY ',I5)
      STOP

 40   CONTINUE
      PRINT 43,KRAY
 43   FORMAT (5X,'***CHANGE IN NUMBER OF GATES -- RAY ',I5)
      STOP

 50   CONTINUE
      PRINT 53,KRAY
 53   FORMAT (5X,'***NEGATIVE RANGE TO FIRST GATE -- RAY ',I5)
      STOP

 60   CONTINUE
      PRINT 63,MAXRNG,KRAY
 63   FORMAT (5X,'***MORE THAN ',I4,' RANGE GATES -- RAY ',I5)
      STOP

 70   CONTINUE
      PRINT 73
 73   FORMAT(5X,'***INVALID INPUT FIELD NAME SPECIFIED')
      STOP

 80   CONTINUE
      PRINT 83,KRAY
 83   FORMAT (5X,'***CHANGE IN FIXED ANGLE WITHIN SWEEP -- RAY ',I5)
      STOP

 90   CONTINUE
      PRINT 93,KRAY
 93   FORMAT (
     X     5X,'***NON-CONFORMITY IN FIELD STRUCTURE WITHIN UF RECORD ',
     X        '-- RAY ',I5/8X,'USE RESET COMMAND, CONTACT SPRINT ',
     X        'SPECIALIST, OR BOTH!!!')
      STOP

      END

