      SUBROUTINE CONFLD(RBUF,NPLANE,CON)
C
C        FILLS AN ARRAY WITH THE CONSTANT (CON)
C
      DIMENSION RBUF(NPLANE)
      DO 10 I=1,NPLANE
         RBUF(I)=CON
   10 CONTINUE
      RETURN
      END
