      SUBROUTINE FLAT(KRD,IFLAT)
C
C     THIS SUBROUTINE PROCESSES THE FLTERTH CARD WHICH ALLOWS
C     THE USER TO TURN ON AND OFF THE HEIGHT CORRECTION FOR A
C     RADAR BEAM OVER A CURVED EARTH
C
      CHARACTER*8 KRD(10)
      
      IF (KRD(2).EQ.'ON') THEN
C
C     ENABLE FLAT EARTH MODE
C
         IFLAT = 1
         WRITE(*,105)
 105     FORMAT(//5X,'SUMMARY OF FLTERTH COMMAND')
         WRITE(*,110)
 110     FORMAT(5X,'------- -- ------- -------')
         WRITE(*,140)
 140     FORMAT(5X,'FLAT EARTH OPTION ENABLED. ',/,5X,
     X          'NO CORRECTIONS FOR CURVED EARTH OR REFRACTION WILL',
     X          ' BE DONE')
      ELSE 
C
C     DISABLE FLAT EARTH MODE
C
         IFLAT = 0
         WRITE(*,105)
         WRITE(*,110)
         WRITE(*,150)
 150     FORMAT(5X,'FLAT EARTH OPTION DISABLED. ',/,5X,
     X          'CORRECTIONS FOR CURVED EARTH AND REFRACTION ENABLED')
      END IF
      WRITE(*,*)' '

      RETURN

      END 

         
