      SUBROUTINE IPKDAT(IWRD,IDAT,N,MAXFLD)
C
C     Packs N 16-bit integers into IWRD from IDAT
C     SBYTES moves 16-bit chunks from UNPACKED to PACKED.
C
C     CALL SBYTES (PACKED,UNPACKED,NOFF,NBITS,NSKIP,N)
C
      DIMENSION IDAT(MAXFLD)
      CALL SBYTES(IWRD,IDAT,0,16,0,N)
      RETURN
      END
