      SUBROUTINE IPUT8(IWRD,INDX,IVAL)
C
C     PUT AN 8 BIT QUANTITY INTO A NORMAL WORD
C

      IF (IVAL.GT.127 .OR. IVAL.LT.-128) THEN
         WRITE(*,*)'***INTERNAL PACKING ERROR IN IPUT8. IVAL=',IVAL
         STOP
      END IF
      CALL SBYTES(IWRD,IVAL,((INDX-1)*8),8,0,1)

      RETURN

      END
