      FUNCTION VUNF(VMEA,VNYQ,VEST)
C
C     VMEA=MEASURED RADIAL VELOCITY
C     VUNF=TRUE (UNFOLDED) VELOCITY
C     VEST=AN ESTIMATE OF THE TRUE VELOCITY
C     VNYQ=MAXIMUM UNAMBIGUOUS VELOCITY
C     KFAC=INTEGER UNFOLDING FACTOR
C     VUNF=VMEA+2*KFAC*VNYQ;KFAC=0,+/-1,+/-2,+/-3,....
C
      IF(ABS(VMEA-VEST).GT.VNYQ)THEN
         FAC=(VEST-VMEA)/(2.0*VNYQ)
         IF(FAC.GE.0.0)KFAC=FAC+0.5
         IF(FAC.LT.0.0)KFAC=FAC-0.5
         VUNF=VMEA+2.0*KFAC*VNYQ
      ELSE
         VUNF=VMEA
      END IF
      RETURN
      END
