      SUBROUTINE TAPMES(ITAPE,NST)
C
C
C        TAPMES- PRINTS OUT THE APPROPRIATE STATUS MESSAGE ACCORDING TO THE
C                VALUE IN NST
C
C        ITAPE- TAPE UNIT NUMBER
C        NST- NON-ZERO STATUS CHECK FROM SUBROUTINE INPUTD  (SAME AS RDTAPE)
C
C        ALL PARAMETERS ARE INPUT
C
C
C      DIMENSION MESS(10,5)
      CHARACTER*8 MESS(10,5)
      DATA MESS/'END OF F','ILE ENCO','UNTERED ',7*'        ',
     X   'PARITY E','RROR DET','ECTED   ',7*'        ',
     X   'END OF T','APE ENCO','UNTERED ',7*'        ',
     X   'UNEXPECT','ED RECOR','D ORDER ',7*'        ',
     X   'ACTUAL R','ECORD LE','NGTH DIF','FERS FRO','M EXPECT',
     X   'ED LENGT','H       ',3*'        '/
      PRINT 101, ITAPE,NST, (MESS(I,NST), I=1,10)
  101 FORMAT(///1X,'UNIT NO. ',I2,5X,'STATUS= ',I2,5X,10A8)
      RETURN
      END
