      SUBROUTINE BLDDES(ID,IBUF,NID)
C
C     THIS SUBROUTINE BUILDS A 56 CHARACTER DESCRIPTION OF A
C     VOLUME.
C
      CHARACTER*2 CTEMP
      DIMENSION ID(NID),IBUF(10),ITMP(12)

      CALL CBYTE(MBYTE)
      IF (MBYTE.EQ.0) THEN
C
C     NEED TO SHIFT CHARACTERS TO RIGHT
C
         ITMP(1)=ID(8)
         ITMP(2)=ID(9)
         CALL SHIRBL(ITMP,2)
C
C     PUT IN EXPERIMENT NAME
C
         CALL SBYTES(IBUF,ITMP,0,16,0,2)
         
         ITMP(1)=ID(13)
         ITMP(2)=ID(14)
         ITMP(3)=ID(15)
         CALL SHIRBL(ITMP,3)
C
C     PUT IN RADAR NAME
C
         CALL SBYTES(IBUF,ITMP,32,16,0,3)
C
C     PUT IN STARTING AND ENDING TIMES OF VOLUME
C
         DO 20 I=1,12
            WRITE(CTEMP,10)ID(116+I-1)
 10         FORMAT(I2)
            READ(CTEMP,30)ITMP(I)
 30         FORMAT(A2)
 20      CONTINUE
         CALL SHIRBL(ITMP,12)
         CALL SBYTES(IBUF,ITMP,80,16,0,12)
      ELSE
C
C     NO SHIFTING IS NECESSARY
C

C
C     PUT IN EXPERIMENT NAME
C
         CALL SBYTES(IBUF,ID(8),0,16,0,2)
C
C     PUT IN RADAR NAME
C
         CALL SBYTES(IBUF,ID(13),32,16,0,3)
C
C     PUT IN STARTING AND ENDING TIMES OF VOLUME
C
C
C     PUT IN STARTING AND ENDING TIMES OF VOLUME
C
         DO 70 I=1,12
            WRITE(CTEMP,50)ID(116+I-1)
 50         FORMAT(I2)
            READ(CTEMP,60)ITMP(I)
 60         FORMAT(A2)
 70      CONTINUE
         CALL SBYTES(IBUF,ITMP,80,16,0,12)
      END IF

      RETURN

      END

