      SUBROUTINE FILLAZ(LUN,AZ1,DAZ,AINC,NRHD,NLEN,IBUF,JBUF,JPCK,JREC,
     X                  ICOPLANE,COP,ANGXAX)
C
C        FILLS IN BEAMS OF INFORMATION OVER GAPS IN AN ELEVATION SCAN
C
      DIMENSION IBUF(1),JBUF(1),JPCK(1)
      DATA DTR /0.0174533/
      NB=(ABS(DAZ)/AINC) 
      PRINT *,"NB ",NB
      CALL CSLEEP()
      IF(NB.LE.0) RETURN
C
C        PROCEED WITH FILLING IN SUFFICIENT BEAMS TO APPROXIMATE
C                USER SPECIFIED IDEAL SPACING
C
      DINC=DAZ/FLOAT(NB+1)
      DO 5 I=3,NRHD
         JBUF(I)=IBUF(I)
    5 CONTINUE
      AZOUT=AZ1
C
C        NB IS THE NUMBER OF BEAMS TO GENERATE
C
      DO 10 K=1,NB
         AZOUT=AZ1+ (DINC*K)
         IF(AZOUT.LT.0.0) AZOUT=AZOUT+360.0
         IF (ICOPLANE.EQ.1 .OR. ICOPLANE.EQ.2) THEN
C
C     FOR INTERP TO COPLANE SPACE, CONVERT ANGLE TO AZIM IN COPLANE
C
            AZOUT = AZOUT + (90.0-ANGXAX)
            AZC = (ATAN2(TAN(AZOUT*DTR),COS(COP*DTR))/DTR)
            IF (AZC.LT.0.0) AZC = AZC + 180.0
            AZOUT = AZC
         END IF
         JBUF(1)=AMOD(AZOUT,360.0)*64.0
         JREC=JREC+1
         CALL WRRYDK(JPCK,JBUF,JST,LUN,0,NLEN)
   10 CONTINUE
      RETURN
      END
