      SUBROUTINE GETNAME(IWORD,NAMFLD)
C
C     THIS SUBROUTINE RETURNS AN 8 CHARACTER ASCII NAME FOR THE FIELD
C     ENCODED IN IWORD. (USED ONLY IN FIELD FORMAT PROCESSING)
C
      CHARACTER*8 NAMFLD

      IFLDTYP1=ICEDAND(ICEDSHFT(IWORD,-8),15)
      IFLDTYP2=ICEDAND(ICEDSHFT(IWORD,-12),15)
      IF (IFLDTYP1.NE.0 .AND. IFLDTYP2.EQ.0) THEN
C
C     FIELD CALIBRATED ENGINEERING VALUES
C
         IF (IFLDTYP1.EQ.1) THEN
            NAMFLD='DZNE'
         ELSE IF (IFLDTYP1.EQ.2) THEN
            NAMFLD='VRNE'
         ELSE IF (IFLDTYP1.EQ.3) THEN
            NAMFLD='SWNE'
         ELSE IF (IFLDTYP1.EQ.4) THEN
            NAMFLD='SNR'
         ELSE IF (IFLDTYP1.EQ.5) THEN
            NAMFLD='MHR'
         ELSE IF (IFLDTYP1.EQ.6) THEN
            NAMFLD='NCP'
         ELSE
            WRITE(*,*)'***INVALID FIELD CODE IN GETNAME***'
            STOP
         END IF
         
      ELSE IF (IFLDTYP1.EQ.0) THEN
C
C     FOR UNSCALED COUNT FIELDS
C
         IF (IFLDTYP2.EQ.1) THEN
            NAMFLD='DMNE'
         ELSE IF (IFLDTYP2.EQ.2) THEN
            NAMFLD='ZDR'
         ELSE IF (IFLDTYP2.EQ.6) THEN
            NAMFLD='DBMXH'
         ELSE IF (IFLDTYP2.EQ.7) THEN
            NAMFLD='DBMXV'
         ELSE IF (IFLDTYP2.EQ.8) THEN
            NAMFLD='VEL'
         ELSE IF (IFLDTYP2.EQ.10) THEN
            NAMFLD='VELV'
         ELSE IF (IFLDTYP2.EQ.13) THEN
            NAMFLD='SPECW'
         ELSE
            NAMFLD='DKNE'
         END IF
      ELSE
         NAMFLD=" "
      END IF
      RETURN
      END
