      SUBROUTINE IGETAI(IWRD,IZ,IEL,IRNG)
C
C        UNPACKS ADDITIONAL POSITIONING INFORMATION FROM A PARTIALLY
C                INTERPOLATED CARTESIAN VALUE. THIS INFO IS STORED
C                IN THE UPPER 32-BITS OF IWRD.
C
      DATA MASK08,MASK16/ O'377', O'177777'/
      CALL GBYTES(IWRD,IZ,0,8,0,1)
      CALL GBYTES(IWRD,IEL,8,8,0,1)
      CALL GBYTES(IWRD,IRNG,16,16,0,1)
C      IRNG=ICEDAND(ICEDSHFT(IWRD,-32),MASK16)
C      IEL =ICEDAND(ICEDSHFT(IWRD,-48),MASK08)
C      IZ  =ICEDSHFT(IWRD,-56)
      RETURN
      END
