C+++++LISTING OFF+++++
C     CDIR$ NOLIST
      FUNCTION INTCHK(IBUF,KRSET)
C
C--CHECKS A UF RECORD FOR INTER-FIELD CONFORMITY WITH RESPECT TO:
C         1- RANGE TO FIRST GATE
C         2- GATE SPACING
C         3- NUMBER OF GATES
C
C  IBUF- UF RECORD AS READ AND UNPACKED FROM TAPE  (LOWER 16 BITS/WORD)
C KRSET- .TRUE. IF USER HAS INVOKED THE RANGE RESET OPTION IN SPRINT
C
C         RETURNS: 0 IF OK, >0 OTHERWISE.
C
      INCLUDE 'SPRINT.INC'
c      PARAMETER (MAXFLD=16)

      COMMON /CFLD/NFLDS
      COMMON /CFLDC/ IFIELD(MAXFLD), INTINF(MAXFLD,3)
      CHARACTER*8 INTINF,IFIELD

      DIMENSION IBUF(MAXIN)
      INTEGER CVMGP
      LOGICAL KRSET
      CHARACTER*2 NAMFLD
C
      INORM(I)=CVMGP(I-65536,I,I-32768)
C
      INTCHK=0
C

      IFIRST=1
      IPTD=IBUF(5)
      NFLDSTAP=IBUF(IPTD+2)
      DO 50 I=1,NFLDSTAP
         IPTF=IBUF(IPTD+2+(2*I))
         NAMF=IBUF(IPTD+1+(2*I))
         WRITE(NAMFLD,20)NAMF
 20      FORMAT(A2)
         IYES=0
         DO J=1,NFLDS
            IF (NAMFLD.EQ.IFIELD(J)(1:2)) IYES=1
         END DO
         IF (IYES.EQ.0) GOTO 50
         IF (IFIRST.EQ.1) THEN
            NAME1=IBUF(IPTD+1+(2*I))
            IPTF =IBUF(IPTD+2+(2*I))
            IRGFG=INORM(IBUF(IPTF+2))
            IADFG=INORM(IBUF(IPTF+3))
            ISPFG=IBUF(IPTF+4)
            NGATES=IBUF(IPTF+5)
            IFIRST=0
         ENDIF
         IPTF=IBUF(IPTD+2+(2*I))
         NAMF=IBUF(IPTD+1+(2*I))
         IRGCK=INORM(IBUF(IPTF+2))
         IADCK=INORM(IBUF(IPTF+3))
         ISPCK=IBUF(IPTF+4)
         NGATCK=IBUF(IPTF+5)
         IF(IRGFG.NE.IRGCK.OR.
     X        IADFG.NE.IADCK.OR.
     X        ISPFG.NE.ISPCK    ) THEN
            INTCHK=INTCHK+1
            PRINT 101, NAME1,IRGFG,IADFG,ISPFG,
     X           NAMF,IRGCK,IADCK,ISPCK
 101        FORMAT(' +++  ',A2,'...  FIRST GATE (KM+M)=  (',I5,',',
     X           I5,')   SPACING (M)=',I5,'  +++')
         END IF
         IF(.NOT.KRSET) THEN
            IF(NGATES.NE.NGATCK) THEN
               INTCHK=INTCHK+1
               PRINT 102, NAME1,NGATES,NAMF,NGATCK
 102           FORMAT(' +++  ',A2,'...  # GATES=',I5,'  +++')
            END IF
         END IF
 50   CONTINUE
         


      RETURN
      END
