      SUBROUTINE IPUTAI(IWRD,IZ,IEL,IRNG)
C
C        PACKS ADDITIONAL POSITIONING INFORMATION FROM A PARTIALLY
C              INTERPOLATED CARTESIAN LOCATION INTO THE UPPER 32-BITS
C              OF IWRD.
C
      CALL SBYTES(IWRD,IZ,0,8,0,1)
      CALL SBYTES(IWRD,IEL,8,8,0,1)
      CALL SBYTES(IWRD,IRNG,16,16,0,1)
      

C      IWRD=ICEDOR(ICEDSHFT(IEL,16),IRNG)
C      IWRD=ICEDOR(ICEDSHFT( IZ,24),IWRD)
C      IWRD=ICEDSHFT(IWRD,32)
      RETURN
      END
