      FUNCTION IQUAD(ANGLE)
C
C     DETERMINES WHICH QUADRANT AN ANGLE IS IN AND RETURNS THAT
C     QUADRANT NUMBER.
C
      IF (ANGLE.GE.0.0 .AND. ANGLE.LT.90.0) THEN
         IQUAD=1
      ELSE IF (ANGLE.GE.90.0 .AND. ANGLE.LT.180.0) THEN
         IQUAD=2
      ELSE IF (ANGLE.GE.180.0 .AND. ANGLE.LT.270.0) THEN
         IQUAD=3
      ELSE IF (ANGLE.GE.270.0 .AND. ANGLE.LT.360.0) THEN
         IQUAD=4
      ELSE
         IQUAD=-1
      END IF

      RETURN

      END




         
