      SUBROUTINE SCNEND(ITYP)
C
C        POSITIONS INPUT FILE PAST THE END OF DATA.
C                  IF ITYP=0, END OF ELEVATION SCAN.
C                         =1, END OF    VOLUME SCAN.
C
      INCLUDE 'SPRINT.INC'
c      PARAMETER (NIOB=85000,MAXIN=8500,MAXLEN=MAXIN/4)

      COMMON /IO/KPCK(NIOB),NWORD(MAXIN,3),KAZ(3),KAZC,KAZP,IDIR,
     X     ITMDIF,IHR,IMIN,ISEC,IREC,IBEGT(4),NSTBM,NRDOPT,ILSTREC
      IF(ITYP.NE.0) GO TO 95
C
C        POSITION TO END OF ELEVATION SCAN
C
   10 CONTINUE
      IF(NSTBM.NE.0) GO TO 90
      CALL BEAMIN
      GO TO 10
   90 CONTINUE
      RETURN
   95 CONTINUE
C
C        POSITION TO END OF VOLUME SCAN
C
      RETURN
      END
