      SUBROUTINE TAPOUT(IUN,IBUF,LEN,IBLK,IPACK,NST)
C
C        PACK AND WRITE TO TAPE IN BLOCKS OF IBLK 16 BIT WORDS
C
      DIMENSION IBUF(LEN)
 
      DATA IBIT,NBITS,NSKIP,MODE,NTYPE/0,16,0,1,2/
 
      write(*,20)
 20   format(//,5x,'***in tapout***')
      CALL SBYTES(IBUF,IBUF,IBIT,NBITS,NSKIP,LEN)
      IRP=(LEN-1)/IBLK + 1
      IAT=1
      DO 100 I=1,IRP
      LN=(MIN0(LEN-(I-1)*IBLK,IBLK)-1)/4+1
C         CALL WRTAPE(IUN,MODE,NTYPE,IBUF(IAT),LN)
C         CALL IOWAIT(IUN,NST,NWDS)
      IAT=IAT+LN
         IF (NST.NE.0) RETURN
 100  CONTINUE
      RETURN
      END
