      SUBROUTINE TPQERX(IENUM,ITYP)
C
C        ERROR RECOVERY INTERFACE VAX-VMS SPECIFIC
C
C
C
C  ERROR             ERROR                                               SUB-
C NUMBER            MESSAGE                                            ROUTINE
C
C  301   ERROR OPENING AND READING RADAR (.RAD) FILE                   POSINT
C  302   ERROR READING VOLUME HEADER ON RADAR (.RAD) FILE              SETVOL
C  303   ERROR ESTABLISHING CARTESIAN (.CAR) FILE FOR OUTPUT           SETOUT
C  304   ERROR READING DATA FROM RADAR (.RAD) FILE                     BEAMIN
C  305   ERROR READING DATA FROM CARTESIAN (.CAR) FILE                 FETCHZ
C  306   CANNOT MATCH SECTOR SCAN WITH CARTESIAN GRID LOCATIONS        RSCART
C  307   CANNOT MATCH SECTOR SCAN WITH INTERPOLATED GRID LOCATIONS     SCNSET
C  308   ERROR ACCESSING EXISTING CARTESIAN (.CAR) FILE                SETCRT
C  309   ERROR OPENING SCRATCH FILE FOR INTERPOLATION                  TRPVOL
C  310   ERROR OPENING CARTESIAN (.CAR) FILE                           SETOUT
C  311   CANNOT MATCH ELEVATION SCAN SEQUENCE WITH CARTESIAN GRID      TRPVOL
C  312   ERROR LOCATING FIRST BEAM IN ELEVATION SCAN                   TRPVOL
C  313   ERROR LOCATING SECOND BEAM IN ELEVATION SCAN                  TRPVOL
C  314   ERROR WRITING TO SCRATCH FILE                                 TRPVOL
C  315   MAXIMUM SCRATCH FILE RECORD COUNT EXCEEDED                    TRPVOL
C  316   ERROR WRITING DATA TO CARTESIAN (.CAR) FILE                   TRPVOL
C  317   ERROR READING FROM SCRATCH FILE                               TRPVOL
C  318   MAXIMUM CARTESIAN (.CAR) FILE RECORD COUNT EXCEEDED           TRPVOL
C  319   ERROR WRITING CARTESIAN (.CAR) FILE HEADER RECORD             TRPVOL
C  320   ERROR OPENING MUDRAS (.MUD) FILE                              MUDWRT
C  321   ERROR WRITING DATA TO MUDRAS (.MUD) FILE                      MUDWRT
C  322   ERROR WRITING MUDRAS (.MUD) FILE HEADER RECORD                MUDWRT
C  323   LESS THAN 2 ELEVATION SCANS IN VOLUME                         SETVOL
C  324   OUTPUT LOGICAL UNIT NUMBER MUST BE IN THE RANGE 1-99          OUTFIL
C  325   IMPROPER OUTPUT TAPE POSITIONING CODE                         OUTFIL
C  326   DATE TO PROCESS MUST BE SPECIFIED                             PROFIL
C  327   SUBSECTIONING ALONG RANGE IMPROPERLY SPECIFIED                RNGFIL
C  328   INPUT VELOCITY VALUES OUTSIDE THE NYQUIST RANGE-
C         UNFOLDING CANNOT BE PERFORMED                                TRPD
C  329   TOO MANY BEAMS/SCAN                                           UFNCAR
C  330   NYQUIST=0.0 AND NEEDS TO BE USED                              METHOD
C
C
C
C
C   BY: MARTA ORYSHCHYN
C
C     THIS SUBROUTINE PRINTS A DIAGNOSTIC ERROR MESSAGE
C        CORRESPONDING TO THE VALUE OF IENUM.
C     ERRMSG WILL TERMINATE THE PROGRAM IF THE ERROR
C        IS FATAL BY ATTEMPTING TO DIVIDE BY ZERO.
C
      DATA IZERO/0/
C
C  FIND THE PROPER ERROR NUMBER AND GO TO THAT MESSAGE:
C
      write(8,*)'TPQERX: ienum,ityp=',ienum,ityp
      IBRAN = IENUM - 300
C
      GO TO (301,302,303,304,305,306,307,308,
     X       309,310,311,312,313,314,315,316,
     X       317,318,319,320,321,322,323,324,
     X       325,326,327,328,329,330) IBRAN
C
C
301   CONTINUE
      PRINT 401
401   FORMAT(/1X,'+++  ERROR OPENING AND READING  +++')
      PRINT 501
501   FORMAT(1X,'+++      RADAR (.RAD) FILE      +++'/)
      GO TO 700
C
302   CONTINUE
      PRINT 402
402   FORMAT(/1X,'+++  ERROR READING VOLUME HEADER  +++')
      PRINT 502
502   FORMAT(1X,'+++     ON RADAR (.RAD) FILE      +++'/)
      GO TO 700
C
303   CONTINUE
      PRINT 403
403   FORMAT(/1X,'+++  ERROR ESTABLISHING CARTESIAN  +++')
      PRINT 503
503   FORMAT(1X,'+++     (.CAR) FILE FOR OUTPUT     +++'/)
      GO TO 700
C
304   CONTINUE
      PRINT 404
404   FORMAT(/1X,'+++  ERROR READING DATA FROM  +++')
      PRINT 504
504   FORMAT(1X,'+++    RADAR (.RAD) FILE      +++'/)
      GO TO 700
C
305   CONTINUE
      PRINT 405
405   FORMAT(/1X,'+++  ERROR READING DATA FROM  +++')
      PRINT 505
505   FORMAT(1X,'+++   CARTESIAN (.CAR) FILE   +++'/)
      GO TO 700
C
306   CONTINUE
      PRINT 406
406   FORMAT(/1X,'+++  CANNOT MATCH SECTOR SCAN WITH  +++')
      PRINT 506
506   FORMAT(1X,'+++     CARTESIAN GRID LOCATIONS    +++'/)
      GO TO 700
C
307   CONTINUE
      PRINT 407
407   FORMAT(/1X,'+++  CANNOT MATCH SECTOR SCAN WITH  +++')
      PRINT 507
507   FORMAT(1X,'+++   INTERPOLATED GRID LOCATIONS   +++'/)
      GO TO 700
C
308   CONTINUE
      PRINT 408
408   FORMAT(/1X,'+++  ERROR ACCESSING EXISTING  +++')
      PRINT 508
508   FORMAT(1X,'+++   CARTESIAN (.CAR) FILE    +++'/)
      GO TO 700
C
309   CONTINUE
      PRINT 409
409   FORMAT(/1X,'+++  ERROR OPENING SCRATCH FILE  +++')
      PRINT 509
509   FORMAT(1X,'+++      FOR INTERPOLATION       +++'/)
      GO TO 700
C
310   CONTINUE
      PRINT 410
410   FORMAT(/1X,'+++  ERROR OPENING CARTESIAN (.CAR) FILE  +++'/)
      GO TO 700
C
311   CONTINUE
      PRINT 411
411   FORMAT(/1X,'+++  CANNOT MATCH ELEVATION SCAN SEQUENCE  +++')
      PRINT 511
511   FORMAT(1X,'+++          WITH CARTESIAN GRID           +++'/)
      GO TO 700
C
312   CONTINUE
      PRINT 412
412   FORMAT(/1X,'+++  ERROR LOCATING FIRST BEAM  +++')
      PRINT 512
512   FORMAT(1X,'+++      IN ELEVATION SCAN      +++'/)
      PRINT 406
      PRINT 506
      GO TO 700
C
313   CONTINUE
      PRINT 413
413   FORMAT(/1X,'+++  ERROR LOCATING SECOND BEAM  +++')
      PRINT 513
513   FORMAT(1X,'+++      IN ELEVATION SCAN       +++'/)
      PRINT 407
      PRINT 507
      GO TO 700
C
314   CONTINUE
      PRINT 414
414   FORMAT(/1X,'+++  ERROR WRITING TO SCRATCH FILE  +++'/)
      GO TO 700
C
315   CONTINUE
      PRINT 415
415   FORMAT(/1X,'+++  MAXIMUM SCRATCH FILE RECORD  +++')
      PRINT 515
515   FORMAT(1X,'+++       COUNT EXCEEDED          +++'/)
      GO TO 700
C
316   CONTINUE
      PRINT 416
416   FORMAT(/1X,'+++  ERROR WRITING DATA TO  +++')
      PRINT 516
516   FORMAT(1X,'+++  CARTESIAN (.CAR) FILE  +++'/)
      GO TO 700
C
317   CONTINUE
      PRINT 417
417   FORMAT(/1X,'+++  ERROR READING FROM SCRATCH FILE  +++'/)
      GO TO 700
C
318   CONTINUE
      PRINT 418
418   FORMAT(/1X,'+++  MAXIMUM CARTESIAN (.CAR) FILE  +++')
      PRINT 518
518   FORMAT(1X,'+++      RECORD COUNT EXCEEDED      +++'/)
      GO TO 700
C
319   CONTINUE
      PRINT 419
419   FORMAT(/1X,'+++  ERROR WRITING CARTESIAN (.CAR)  +++')
      PRINT 519
519   FORMAT(1X,'+++       FILE HEADER RECORD         +++'/)
      GO TO 700
C
320   CONTINUE
      PRINT 420
420   FORMAT(/1X,'+++  ERROR OPENING MUDRAS (.MUD) FILE  +++'/)
      GO TO 700
C
321   CONTINUE
      PRINT 421
421   FORMAT(/1X,'+++  ERROR WRITING DATA TO  +++')
      PRINT 521
521   FORMAT(1X,'+++    MUDRAS (.MUD) FILE   +++'/)
      GO TO 700
C
322   CONTINUE
      PRINT 422
422   FORMAT(/1X,'+++  ERROR WRITING MUDRAS (.MUD)  +++')
      PRINT 522
522   FORMAT(1X,'+++      FILE HEADER RECORD       +++'/)
      GO TO 700
C
323   CONTINUE
      PRINT 423
423   FORMAT(/1X,'+++  LESS THAN 2 ELEVATION SCANS IN VOLUME  +++'/)
      GO TO 700
C
324   CONTINUE
      PRINT 424
424   FORMAT(/1X,'+++  OUTPUT LOGICAL UNIT NUMBER MUST ',
     X          'BE IN THE RANGE 1-99  +++'/)
      GO TO 700
C
325   CONTINUE
      PRINT 425
425   FORMAT(/1X,'+++  IMPROPER OUTPUT TAPE POSITIONING ',
     X          'CODE  +++'/)
      GO TO 700
C
326   CONTINUE
      PRINT 426
426   FORMAT(/1X,'+++  DATE TO PROCESS MUST BE ',
     X          'SPECIFIED  +++'/)
      GO TO 700
C
327   CONTINUE
      PRINT 427
427   FORMAT(/1X,'+++  SUBSECTIONING ALONG RANGE ',
     X          'IMPROPERLY SPECIFIED  +++'/)
      GO TO 700
328   CONTINUE
      PRINT 428
428   FORMAT(/1X,'+++  INPUT VELOCITY VALUES OUTSIDE THE NYQUIST RANGE',
     X           ' - UNFOLDING CANNOT BE PERFORMED +++')
      GO TO 700
  329 CONTINUE
      PRINT 429
  429 FORMAT(/' +++  MAXIMUM NUMBER OF BEAMS/ELEVATION SCAN EXCEEDED',
     X        '  +++'/)
      GO TO 700
  330 CONTINUE
      PRINT 430
  430 FORMAT(/' +++  NYQUIST VELOCITY = 0.0'/
     X          14X,'--  UNFOLDING CANNOT BE PERFORMED'/
     X          14X,'--  QUAL FIELD CANNOT BE COMPUTED  +++'/)
      GO TO 700
C
C
C  IF ITYP.EQ.0 THEN THE ERROR IS NOT FATAL,
C     SO THE ROUTINE JUST RETURNS THE ERROR
C     MESSAGE WITHOUT TERMINATING THE PROGRAM:
C
700   IF ( ITYP.EQ.0 )    RETURN
C
C
C  IF ITYP.EQ.1 THEN THE ERROR IS FATAL,
C     AND THE PROGRAM IS FORCED TO TERMINATE
C     BY ATTEMPTING TO DIVIDE BY ZERO:
C
      IF ( ITYP.EQ.1 ) THEN
        ITYP = ITYP / IZERO
      END IF
C
C
      RETURN
C
      END
