      SUBROUTINE DATAIN(LIUN,A,LIJ,IT,ZIP,SCALE,IUN)
C
C        INTERFACE FOR READING PACKED (16-BIT) DATA RECORDS
C
C        LIUN- LOGICAL UNIT NUMBER
C        A- DESTINATION ARRAY TO RECEIVE THE DATA VALUES IN PROPER 64-BIT FORM
C        LIJ- NUMBER OF DATA VALUES TO RETURN (16 BIT)
C        IT- WORKING STORAGE FOR UNPACKING PACKED DATA RECORDS
C        ZIP- VALUE IN PROGRAM TO INDICATE MISSING DATA VALUES
C        SCALE- SCALE FACTOR TO ADJUST PACKED VALUES TO PROPER UNITS
C        IUN- TAPE STATUS FLAG
C
      DIMENSION A(1), IT(1)
      DATA NBKI/3200/
      DATA IZIPAK,MODE,NTYPE/32768,1,2/
      ISIXT(NUM)=(NUM-1)/4 + 1.01
C        READ IN AN PACKED RECORD AND CONVERT TO PROPER REPRESENTATION
      MXLEN=ISIXT(NBKI)
      M2=0
   10 CONTINUE
      M1=M2+1
      M2=M2+NBKI
      IF(M2.GT.LIJ) M2=LIJ
      MEN=M2-M1+1
c      CALL RDTAPE(LIUN,MODE,NTYPE,A(M1),MXLEN)
c      CALL IOWAIT(LIUN,NST,NWDS)
      IF(NST.NE.0) RETURN
      CALL GBYTES(A(M1),IT,0,16,0,MEN)
      M=M1-1
      DO 15 I=1,MEN
         M=M+1
         A(M)=ZIP
         IF(IT(I).EQ.IZIPAK) GO TO 15
         IX=IT(I)
         IT(I)=CVMGP(IX-65536,IX,IX-32768)
         A(M)=IT(I)*SCALE
   15 CONTINUE
      IF(M2.LT.LIJ) GO TO 10
      RETURN
      END
