      SUBROUTINE DEFINE(KRD)
C
C        PROCESS DEFINE COMMAND
C           -CHILD OF KARDIN ROUTINE
C
      PARAMETER (MXCARD=10000,MXDEF=25,MXSUB=100,NREC=5)
      COMMON /DEFVAL/ KIMAGE(MXCARD),NAMBLK(MXDEF),LOCST(MXDEF)
     X               ,LENBLK(MXDEF),NDBLK,ISTORE,IXPAND(NREC)
     X               ,NXPAND(NREC),IX,IVSTAK(2,MXSUB),NSUB,ISFLG,ICFLG
      CHARACTER*8 KIMAGE,NAMBLK,IVSTAK
      COMMON /UNITS/ LIN,LOUT,LPR,LSPOOL
      CHARACTER*(*) KRD(10)
C
C        CHECK FOR DUPLICATE DEFINE BLOCK NAME
C
      IF(KRD(1).EQ.'DEFEND') THEN
         CALL CEDERX(548,1)
         RETURN
      END IF
      IF(NDBLK.EQ.0) GO TO 25
C READ INTO INT ARRAY FOR USE WITH INTS
   10 FORMAT(A8)
      DO 20 I=1,NDBLK
         IF(KRD(2).EQ.NAMBLK(I)) THEN
            CALL CEDERX(555,1)
            RETURN
         END IF
   20 CONTINUE
   25 CONTINUE
      IF (NDBLK.EQ.MXDEF) THEN
         CALL CEDERX(546,1)
         RETURN
      END IF
      NDBLK=NDBLK+1
      NAMBLK(NDBLK)=KRD(2)
      LOCST(NDBLK)=ISTORE+1
      LENBLK(NDBLK)=0
C
C        LOOP TO READ AND STORE CARD
C
 100  CONTINUE
      CALL RDKARD(KRD)
      WRITE(LPR,601) KRD
  601 FORMAT(' >>>>>',10A8,'<<<<<')
      IF(KRD(1).EQ.'DEFEND') GO TO 200
      IF(KRD(1).EQ.'DEFINE') THEN
         CALL CEDERX(548,1)
         RETURN
      END IF
      IF (ISTORE.GE.MXCARD) THEN
         CALL CEDERX(547,1)
         RETURN
      END IF
C  TRANSF TO INT ARRAY
      CALL COPCX(KIMAGE(ISTORE+1),KRD,10)
      ISTORE=ISTORE+10
      LENBLK(NDBLK)=LENBLK(NDBLK)+1
      GOTO 100
C
C        END OF DEFINE BLOCK FOUND
C
 200  CONTINUE
      RETURN
      END

