      SUBROUTINE LSFILW(RBUF,OBUF,NX,NY,IBEG,IEND,JBEG,JEND,BAD)
C
C        GLOBAL DATA FILLING OF A WINDOWED REGION
C
      DIMENSION RBUF(NX,NY),OBUF(NX,NY)
      CALL EXTEND(OBUF,NX,NY,1,BAD)
C
C        COPY FILLED REGION TO OUTPUT BUFFER
C
      DO 10 J=JBEG,JEND
      DO 10 I=IBEG,IEND
         RBUF(I,J)=OBUF(I,J)
   10 CONTINUE
      RETURN
      END
