      SUBROUTINE MAXZ (CAPA, NDX, NX, NY, ZMAX, BAD)
C
C        LOCATES THE MAXIMUM VALUE IN A 2- ARRAY
C                ALSO RETURNS THE INDICES OF ITS LOCATION.
C
      DIMENSION  CAPA(NDX,NY)
      DIMENSION  ZMAX(3)
C
      DO 500 J=1,NY
      DO 500 I=1,NX
      VAL=CAPA(I,J)
      IF(VAL.EQ.BAD.OR.VAL.LT.ZMAX(1)) GO TO 500
      ZMAX(1) = VAL
      ZMAX(2)=I
      ZMAX(3)=J
500   CONTINUE
      RETURN
      END
