      SUBROUTINE STINT(NAMF,IFIXAX,LCAX,IPR)
C
C        WRITES OUT A HEADER FOR STATISTICAL SUMMARIES
C
      COMMON /AXUNTS/ IUNAXS,LABAXS(3,3),SCLAXS(3,3),AXNAM(3)
      CHARACTER*4 AXNAM
      CHARACTER*2 NAMF(4)
      CHARACTER*2 LCAX
      WRITE(IPR,2002) NAMF,LCAX,LABAXS(IFIXAX,IUNAXS)
      WRITE(99,2002) NAMF,LCAX,LABAXS(IFIXAX,IUNAXS)
 2002 FORMAT(/1X,4A2,1X,A2,' ',A4,5X,'MEAN',4X,'STDV',6X,'N',3X,
     X   'I1  I2  J1  J2',8X,'MIN',5X,'MAX')
      RETURN
      END
