      SUBROUTINE ASDPMD (IA,IB,NRP)
C  TO CONVERT UNPACKED ASCII CODES TO ALPHANUMERIC CHARACTERS
      DIMENSION IA(1),IB(1)
C      DATA I6BL/6R      /
      DO 10 I=1,NRP
         IB(I)=LSHIFT(IA(I),16)
C
C     THE FOLLOWING COMMENTED COMMAND IS USED IN THE CRAY VERSION.
C     I'M NOT SURE WHAT IT DOES, HOWEVER.
C         IB(I)=OR(IB(I),I6BL)
 10   CONTINUE
      RETURN
      END
