      SUBROUTINE MYDATE(DATVAL)
C
C     RETURNS THE DATE IN ASCII FORM MM/DD/YY
C
      CHARACTER*8 DATVAL
      INTEGER IARRAY(3)

      CALL IDATE(IARRAY)
      IARRAY(3)=MOD(IARRAY(3),1900)
      WRITE(DATVAL,20)IARRAY(2),IARRAY(1),IARRAY(3)
 20   FORMAT(I2,'/',I2,'/',I2)

      RETURN

      END

      SUBROUTINE CLOCK(TIMVAL)
C
C     RETURNS THE CURRENT TIME IN ASCII FORM HH:MM:SS
C
      CHARACTER*8 TIMVAL
      INTEGER IARRAY(3)

      CALL ITIME(IARRAY)
      WRITE(TIMVAL,20)IARRAY(1),IARRAY(2),IARRAY(3)
 20   FORMAT(I2,'/',I2,'/',I2)

      RETURN

      END


      FUNCTION CVMGT(TRANS,FLANS,LTEST)
C
C     THIS FUNCTION RETURNS TRANS IF LTEST IS TRUE
C                   RETURNS FLANS IF LTEST IS FALSE
C
      LOGICAL LTEST
C      INTEGER TRANS,FLANS

      IF (LTEST) THEN
         CVMGT=TRANS
      ELSE
         CVMGT=FLANS
      END IF

      RETURN

      END


      INTEGER FUNCTION CVMGP(I1,I2,I3)
C
C     RETURNS I1 IF I3 >= 0
C     RETURNS I2 IF I3 <  0
C
      IF (I3.GE.0.0) THEN
         CVMGP=I1
      ELSE
         CVMGP=I2
      END IF

      RETURN

      END

      INTEGER FUNCTION CVMGZ(I1,I2,I3)
C
C     RETURNS I1 IF I3 = 0.0
C     RETURNS I2 IF I3 != 0.0
C
      IF (I3.EQ.0.0) THEN
         CVMGZ=I1
      ELSE
         CVMGZ=I2
      END IF

      RETURN

      END

      INTEGER FUNCTION CVMGN(I1,I2,I3)
C
C     RETURNS I1 IF I3 != 0.0
C     RETURNS I2 IF I3 =  0.0
C
      IF (I3.NE.0.0) THEN
         CVMGN=I1
      ELSE
         CVMGN=I2
      END IF

      RETURN

      END
