      SUBROUTINE SHIRBL(NAME,NNAM)
C
C        SHIFT DATA 16 PLACES RIGHT AND ZERO FILL
C
      DIMENSION NAME(NNAM)
      DO 100 I=1,NNAM
         NAME(I)=RSHIFT(NAME(I),16)
 100  CONTINUE
      RETURN
      END
