c
c----------------------------------------------------------------------X
c
      SUBROUTINE SAVANGL(INDAT,NAMFLD,IFLD,NFLDS,PAMN,PAMX,PRMN,PRMX,
     X                   RSKIP,IANAM,AFMN,AFMX,AREF,APROC,ACNT,AGAP,
     X                   AERR,APRNT,NAP)
C
C  CONTINUE READING PLTANGL STACK FOR FIELDS TO BE PLOTTED
C
C     NAP       - NUMBER OF FIELDS PER FRAME
C     IANAM     - NAMES   "    "
C     AFMN,AFMX - MINIMUM AND MAXIMUM FIELD VALUE
C     AREF      - DASHED REFERENCE LINE ON PLOTS
C     APROC     - NAME FOR SPECIAL PROCESSING (E.G., VAD)
C     APRNT     - PRINT THIS FIELD IF APRNT=PRNT
C     ACNT      - MINIMUM NUMBER OF GOOD DATA POINTS FOR VAD ANALYSIS
C     AGAP      - MAXIMUM ALLOWED AZIMUTH GAP         "   "      "
C     AERR      -    "       "    RMS DIFFERENCE BETWEEN INPUT AND VAD WINDS
C     PAMN,PAMX - MINIMUM AND MAXIMUM ANGLES (DEG)
C     PRMN,PRMX -    "     "     "    RANGES (KM)
C     RSKIP     - RANGE SKIPPING FACTOR WITHIN THE SWEEP
C
C
      INCLUDE 'dim.inc'

      CHARACTER*8 INDAT(10),JNDAT(10)
      CHARACTER*8 NAMFLD(MXF),IANAM(MXF),APROC(MXF),APRNT(MXF)
      CHARACTER*4 NAMOUT
      DATA NAMOUT/'    '/
      DIMENSION IFLD(MXF)
      DIMENSION AFMN(MXF),AFMX(MXF),AREF(MXF),ACNT(MXF),AGAP(MXF),
     +   AERR(MXF)
      DIMENSION AFYB(MXF),AFYT(MXF)

      NAP=0
      WRITE(6,11)(INDAT(I),I=2,10)
   11 FORMAT(1X,'PANGL: ',9A8)
      READ(INDAT,13)PAMN,PAMX,PRMN,PRMX,RSKIP
   13 FORMAT(/F8.0/F8.0/F8.0/F8.0/F8.0)

C     READ FIELD NAME, MIN VALUE, MAX VALUE UNTIL END-OF-STACK
C
   20 READ(5,21)(JNDAT(I),I=1,10)
   21 FORMAT(10A8)
c      WRITE(6,22)(JNDAT(I),I=1,10)
c   22 FORMAT('Kardin=',10A8)
      IF(JNDAT(1)(1:1).EQ.'*')GO TO 20
      IF(JNDAT(1).EQ.'END     ')RETURN
      IF(JNDAT(1).NE.'        ')THEN
         WRITE(6,23)
   23    FORMAT(1X,'*** SAVANGL: NO END LINE ENCOUNTERED ***')
         STOP
      END IF
      NAP=NAP+1
      IF(NAP.GT.12)THEN
         WRITE(6,25)
   25    FORMAT(1X,'*** SAVANGL: NO. PLOTS EXCEEDS 12 - STOP ***')
         STOP
      END IF
      READ(JNDAT,27)IANAM(NAP),AFMN(NAP),AFMX(NAP),AREF(NAP),APROC(NAP),
     +     ACNT(NAP),AGAP(NAP),AERR(NAP),APRNT(NAP)
   27 FORMAT(/A8/F8.0/F8.0/F8.0/A8/F8.0/F8.0/F8.0/A8)
C
      CALL FIELD(IANAM(NAP),NAMFLD,NFLDS,NAMOUT)
      IFL=IFIND(IANAM(NAP),NAMFLD,NFLDS)
      WRITE(6,29)NAP,NAMFLD(IFL),IFL,IFLD(IFL),AFMN(NAP),AFMX(NAP),
     +           AREF(NAP),APROC(NAP),ACNT(NAP),AGAP(NAP),AERR(NAP),
     +           APRNT(NAP)
   29 FORMAT(8X,'NAP= ',I4,4X,A8,2I4,3F8.2,1X,A6,1X,3F8.2,2X,A8)
C      IF(IFLD(IFL).LE.-1)THEN
C         WRITE(6,31)
C   31    FORMAT(1X,'*** THIS TYPE OF FIELD NOT ALLOWED ***')
C         NAP=NAP-1
C      END IF
      GO TO 20
      END








