      SUBROUTINE AIRACCUM(FLD,LOC,NPT,FIELD,INUM,IX,IY,IZ,
     X     IXLOC,IYLOC,IZLOC,IACT,ICNT)

C
C     ACCUMULATES THE AIRCRAFT DATA AT CLOSEST GRID LOCATIONS FOR LATER
C     AVERAGING.
C
      PARAMETER (MXL=20000,NFLDS=3,MXPT=5000)
      DIMENSION FLD(MXL)
      DIMENSION IX(MXPT),IY(MXPT),IZ(MXPT),FIELD(MXPT,NFLDS)
      DIMENSION ICNT(MXPT)


      IF (LOC.EQ.0) THEN
C     NEW OUTPUT POINT IS BEING ACCUMULATED TO
         FIELD(NPT,INUM)=FLD(IACT)
      ELSE
C     POINT TO WHICH DATA HAS ALREADY BEEN WRITTEN IS BEING WRITTEN TO
         FIELD(LOC,INUM)=FIELD(LOC,INUM)+FLD(IACT)
      END IF

      RETURN

      END
