      SUBROUTINE FLDNAMOUT(ID)
C     
C     THIS SUBROUTINE OUTPUTS THE CURRENT EDIT FIELD NAMES TO AN ASCII
C     STRING AND SENDS IT TO A ROUTINE FOR OUTPUT TO A FILE THAT WILL BE
C     READ BY THE CEDRIC GUI. EVERYTIME THE LIST OF FIELD
C     NAMES CHANGES IN CEDRIC, THIS ROUTINE SHOULD BE CALLED.
C
      INCLUDE 'CEDRIC.INC'
      PARAMETER (IUNIT=7)
      DIMENSION ID(NID)
      CHARACTER*200 FIELDLIST

      FIELDLIST='             '
      WRITE(FIELDLIST,10) (ID(176+(I-1)*5),ID(177+(I-1)*5),
     .     ID(178+(I-1)*5),ID(179+(I-1)*5),I=1,NFMAX)
 10   FORMAT(100A2)


      CALL CEDGUI('ASYNC','updatfldlist')
      CALL CEDGUI('ASYNC',FIELDLIST)
      RETURN
      END

C**************************************************************
      SUBROUTINE CEDGUI(TYPE,STRING)
C
C     PASSES INFO TO THE CEDRIC GUI BY WRITING INFO TO A FILE
C

      INCLUDE 'CEDRIC.INC'
      CHARACTER*(*) TYPE,STRING
      PARAMETER (IUNITA=7, IUNITS=8)
      DATA IFIRST/1/

      IF (IFIRST.EQ.1) THEN
         OPEN(UNIT=IUNITA, FILE='.async', STATUS='UNKNOWN')
         OPEN(UNIT=IUNITS, FILE='.sync', STATUS='UNKNOWN')
         IFIRST=0
      END IF

      IF (TYPE.EQ.'ASYNC') THEN
         WRITE(IUNITA,10)STRING
 10      FORMAT(A)
         CALL FLUSH(IUNITA)
      ELSE IF (TYPE.EQ.'SYNC') THEN
         WRITE(IUNITS,10)STRING
         CALL FLUSH(IUNITS)
      END IF
      
      RETURN
      END
