      SUBROUTINE LBFILL(IFTP,XCRA,YCRA,NCRA,INDX)
C
C     THIS SUBROUTINE FILLS THE LABEL BARS WITH GREY SHADES(HALFTONES)
C
      DIMENSION XCRA(*),YCRA(*)
      DIMENSION DST(4100),IND(4200)

      IF (INDX.NE.0) CALL SFSGFA (XCRA,YCRA,NCRA,DST,4100,IND,4200,
     X                            INDX)


      RETURN

      END
      
