      SUBROUTINE PLNFLD(IFIXAX,L1,L2,NFDSP)
C
C        DETERMINES THE MIN,MAX LEVELS TO PROCESS, THE FIXED AXIS
C                   AND THE NUMBER OF ACTIVE DISPLAY FIELDS.
C
      INCLUDE 'CEDRIC.INC'
      COMMON /DSPECS/ IWIND(2,3),PWIND(2,3),NCWORD(3),IFLDW(NFMAX),
     X                SCLFAC(NFMAX),NSYMCD(2,NFMAX),WIDCD(NFMAX),
     X                ZREFCD(NFMAX),THKLIN(NFMAX)
      IFIXAX=NCWORD(3)
      L1=IWIND(1,IFIXAX)
      L2=IWIND(2,IFIXAX)
      NFDSP=0
      DO 10 I=1,NFMAX
         IF(IFLDW(I).EQ.0) GO TO 10
         NFDSP=NFDSP+1
   10 CONTINUE
      RETURN
      END
