C
C     THE FUNCTIONS IN THIS SUBROUTINE ISOLATE THE REST OF THE CEDRIC
C     CODE FROM MACHINE DIFFERENCES IN FORTRAN LOGICAL FUNCTIONS.
C     (WORKS ON HP)
C
      FUNCTION ICEDAND(I1,I2)
C
C     SUBROUTINE TO PERFORM A LOGICAL AND. 
C
      ICEDAND = IAND(I1,I2)
      RETURN
      END

      FUNCTION ICEDOR(I1,I2)
C
C     PERFORM A LOGICAL OR
C
      ICEDOR = IOR(I1,I2)
      RETURN
      END

      FUNCTION ICEDSHFT(I1,I2)
C
C     SHIFT I1 I2 PLACES TO THE LEFT IF I2 >0, TO THE RIGHT IF I2 < 0
C
      ICEDSHFT = ISHFT(I1,I2)
      RETURN
      END

      FUNCTION ICEDXOR(I1,I2)
C
C     EXCLUSIVE OR OF I1,I2
C
      ICEDXOR = IXOR(I1,I2)
      RETURN
      END

      
