      PROGRAM CEDWRITE
C
C     THIS ROUTINE IS A DRIVER FOR WRITING CEDRIC FORMAT FILES.
C     YOU WILL HAVE TO REPLACE THIS PROGRAM AND THE SUBROUTINE FETCHPLANE
C     IN THIS FILE WITH YOUR OWN. THESE ARE JUST EXAMPLES.
C
      PARAMETER (MAXFLD=25, NID=510)
      CHARACTER*4 PROJECT
      CHARACTER*6 SCINAME,NAMLND(7),RADSTN,TAPE
      CHARACTER*8 VOLNAM,FLDNAM(MAXFLD),SOURCE
      DIMENSION ISCLFLD(MAXFLD),XLND(7),YLND(7),ZLND(7)
      DIMENSION IDAT(10,10)

      SCINAME = 'ANDERS'
      BASANG  = 90.0
      VOLNAM  = 'CHECK'
      SOURCE  = 'F06527  '
      IBEGYR  = 92
      IBEGMNT = 3
      IBEGDAY = 9
      PROJECT = 'HARP'
      TAPE    = 'TPNAME'
      RADCON  = 68.23
      VNYQ    = 20.47

      IBEGHR  = 9
      IBEGMIN = 12
      IBEGSEC = 23
      IENDYR  = 92
      IENDMNT = 3
      IENDDAY = 9
      IENDHR  = 10
      IENDMIN = 15
      IENDSEC = 47

      LATDEG = 23
      LATMIN = 47
      LATSEC = 32
      LONDEG = -187
      LONMIN = 23
      LONSEC = 59
      
      XMIN  = 1.
      XMAX  = 10.
      NUMX  = 10
      ISPCX = 1000

      YMIN  = 2.
      YMAX  = 11.
      NUMY  = 10
      ISPCY = 1000

      ZMIN  = 1000.
      ZMAX  = 2000.
      NUMZ  = 2
      ISPCZ = 1000.

      NFLD=1
      FLDNAM(1)  = 'TESTFLD'
      ISCLFLD(1) = 100
      RADSTN     = 'CP-G  '

      NUMLND = 2
      NUMRAD = 1
      NAMLND(1) = 'ORIGIN'
      NAMLND(2) = 'CP-G  '
      XLND(1) = 0.0
      XLND(2) = 5.0
      YLND(1) = 0.0
      YLND(2) = 7.3
      ZLND(1) = 0.0
      ZLND(2) = 0.0


      CALL WRITCED(SCINAME,BASANG,VOLNAM,IBEGYR,
     X     IBEGMNT,IBEGDAY,IBEGHR,IBEGMIN,IBEGSEC,IENDYR,
     X     IENDMNT,IENDDAY,IENDHR,IENDMIN,IENDSEC,XMIN,
     X     XMAX,NUMX,ISPCX,YMIN,YMAX,NUMY,ISPCY,ZMIN,
     X     ZMAX,NUMZ,ISPCZ,NFLD,FLDNAM,ISCLFLD,NUMLND,
     X     NUMRAD,NAMLND,XLND,YLND,ZLND,IDAT,RADSTN,SOURCE,
     X     PROJECT,TAPE,RADCON,VNYQ,LATDEG,LATMIN,LATSEC,
     X     LONDEG,LONMIN,LONSEC)


      
      END


      SUBROUTINE FETCHPLANE(IDAT,NUMX,NUMY,IF,ILEV)
C
C     SAMPLE ROUTINE FOR FETCHING Z PLANES OF CEDRIC DATA.
C     FILLS IN ARRAY WITH BOGUS DATA
C
      DIMENSION IDAT(NUMX,NUMY)

      SCALE=100.

      DO 100 J=1,10
         DO 50 I=1,10
            IDAT(I,J)=I*SCALE
 50      CONTINUE
 100  CONTINUE

      RETURN

      END

         

      
