      PROGRAM DRIVER
C
C     DRIVER ROUTINE FOR READING CEDRIC FILES.
C     REPLACE THIS WITH YOUR OWN PROGRAM.
C
      PARAMETER (MAXX=256,MAXY=256,NUMZ=20,NFLD=2,NID=510)

      DIMENSION ID(NID)
      COMMON /DAT/ FDAT(MAXX,MAXY,NUMZ,NFLD)

      CALL CEDREAD(ID)

      END

      SUBROUTINE PLACEPLANE(RBUF,LF,KOT,FLDNAM,NX,NY)
C
C     SAMPLE ROUTINE. THIS ROUTINE SIMPLY STORES
C     ALL THE DATA IN A SINGLE 4-D ARRAY. REPLACE
C     THIS ROUTINE WITH YOUR OWN.
C
      PARAMETER (MAXX=256,MAXY=256,NUMZ=20,NFLD=2)

      COMMON /DAT/ FDAT(MAXX,MAXY,NUMZ,NFLD)
      DIMENSION RBUF(MAXX,MAXY)
      CHARACTER*8 FLDNAM

      IF (LF.LE.2) THEN
C
C     ONLY STORE DATA FOR FIRST TWO FIELDS IN DATASET.
C
         DO J=1,NY
            DO I=1,NX
               FDAT(I,J,KOT,LF)=RBUF(I,J)
            END DO
         END DO
      END IF

      RETURN

      END


      
